import React,{useState} from 'react';
import { RadioTower,Loader2,Play,RotateCcw,ShieldCheck } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { mutateGsaTvExtended } from '../../lib/gsaTvExtended';
import { updateGsaTvLiveSourceCredentials } from '../../lib/gsaTvLiveSources';
type Props={channelId:string;sources:any[];saving:boolean;onChanged:()=>Promise<void>|void;enqueue:(job:string,payload?:Record<string,unknown>)=>Promise<unknown>|void};
export function GsaTvLiveSources({channelId,sources,saving,onChanged,enqueue}:Props){
 const [busy,setBusy]=useState(false);const [form,setForm]=useState({name:'',protocol:'hls',connection_url:'',public_notes:''});
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const r:any=await mutateGsaTvExtended('save_live_source',{channel_id:channelId,name:form.name,protocol:form.protocol,enabled:true,public_notes:form.public_notes,config:{}});if(form.connection_url.trim())await updateGsaTvLiveSourceCredentials(String(r.id),form.connection_url);toast.success('Fonte ao vivo cadastrada com conexão protegida.');setForm({name:'',protocol:'hls',connection_url:'',public_notes:''});await onChanged();}catch(err:any){toast.error(err?.message||'Falha ao cadastrar fonte.');}finally{setBusy(false);}};
 return <div className="grid gap-4 xl:grid-cols-[390px_1fr]">
  <section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><RadioTower className="h-5 w-5 text-indigo-600"/>Nova fonte ao vivo</h2><form onSubmit={save} className="space-y-3">
   <label className="block text-sm font-semibold">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" placeholder="Ex.: Estúdio principal"/></label>
   <label className="block text-sm font-semibold">Protocolo<select value={form.protocol} onChange={e=>setForm({...form,protocol:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"><option value="hls">HLS</option><option value="rtmp">RTMP</option><option value="rtmps">RTMPS</option><option value="srt">SRT</option></select></label>
   <label className="block text-sm font-semibold">Endereço de conexão<input required type="password" autoComplete="new-password" value={form.connection_url} onChange={e=>setForm({...form,connection_url:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" placeholder={form.protocol==='hls'?'https://.../live.m3u8':`${form.protocol}://...`}/></label>
   <div className="flex gap-2 rounded-lg bg-indigo-50 p-3 text-xs text-indigo-800"><ShieldCheck className="h-4 w-4 shrink-0"/><span>O endereço é criptografado e nunca é lido de volta pelo portal.</span></div>   <label className="block text-sm font-semibold">Observação<input value={form.public_notes} onChange={e=>setForm({...form,public_notes:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" placeholder="Origem, responsável, uso previsto"/></label>
   <button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<RadioTower className="h-4 w-4"/>}Salvar fonte</button>
  </form></section>
  <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="font-black">Fontes cadastradas</h2><button disabled={saving} onClick={()=>void enqueue('live_return')} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><RotateCcw className="h-4 w-4"/>Voltar à programação</button></div>
   {sources.length===0?<div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Nenhuma fonte ao vivo cadastrada.</div>:<div className="space-y-3">{sources.map(s=><div key={s.id} className="flex items-center justify-between gap-4 rounded-xl border p-4"><div><div className="flex items-center gap-2"><strong>{s.name}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${s.state==='live'?'bg-rose-50 text-rose-700':s.connection_configured?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{s.state}</span></div><p className="mt-1 text-xs text-slate-500">{String(s.protocol).toUpperCase()} · {s.connection_configured?'conexão protegida':'sem conexão'}{s.public_notes?` · ${s.public_notes}`:''}</p></div><button disabled={saving||!s.connection_configured||s.state==='live'} onClick={()=>void enqueue('live_take',{source_id:s.id})} className="flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-40"><Play className="h-4 w-4"/>TAKE</button></div>)}</div>}
  </section>
 </div>;
}
