import React, { useState } from 'react';
import { Layers3, Loader2, Plus, Trash2 } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { mutateGsaTvExtended } from '../../lib/gsaTvExtended';
import { configureGsaTvFallback } from '../../lib/gsaTvMediaUpload';

type Props={channelId:string;graphics:any[];media:any[];onChanged:()=>Promise<void>|void;onApply:()=>Promise<void>|void};
export function GsaTvGraphics({channelId,graphics,media,onChanged,onApply}:Props){
  const [busy,setBusy]=useState(false);
  const [fallbackId,setFallbackId]=useState('');
  const [form,setForm]=useState({layer_type:'lower_third',name:'',text_content:'',media_item_id:'',enabled:true});
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await mutateGsaTvExtended('save_graphic',{channel_id:channelId,...form,media_item_id:form.media_item_id||null});toast.success('Camada gráfica salva.');setForm({...form,name:'',text_content:'',media_item_id:''});await onChanged();await onApply();}catch(err:any){toast.error(err?.message||'Falha ao salvar gráfico.');}finally{setBusy(false);}};
  const remove=async(id:string)=>{setBusy(true);try{await mutateGsaTvExtended('delete_graphic',{channel_id:channelId,id});await onChanged();await onApply();toast.success('Camada removida.');}catch(err:any){toast.error(err?.message||'Falha ao remover.');}finally{setBusy(false);}};
  const identity=media.filter(x=>x.state==='ready'&&['identity','program'].includes(x.media_kind));
  return <div className="grid gap-4 xl:grid-cols-[380px_1fr]">
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><Layers3 className="h-5 w-5 text-indigo-600"/>Nova camada</h2>
      <form onSubmit={save} className="space-y-3"><label className="block text-sm font-semibold">Tipo<select value={form.layer_type} onChange={e=>setForm({...form,layer_type:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"><option value="logo">Mosca / logo</option><option value="lower_third">GC / tarja</option><option value="ticker">Ticker</option><option value="bug">Identificador</option></select></label>
      <label className="block text-sm font-semibold">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" placeholder="Ex.: Tarja institucional"/></label>
      <label className="block text-sm font-semibold">Texto<input value={form.text_content} onChange={e=>setForm({...form,text_content:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5" placeholder="Texto exibido no sinal"/></label>      {form.layer_type==='logo'&&<label className="block text-sm font-semibold">Arquivo visual<select value={form.media_item_id} onChange={e=>setForm({...form,media_item_id:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Usar identificador textual</option>{identity.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Ativar ao salvar</label>
      <button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Salvar e aplicar</button></form>
      <div className="mt-6 border-t pt-5"><h3 className="font-black">Tela de emergência</h3><p className="mt-1 text-xs leading-5 text-slate-500">Entra automaticamente no lugar da programação para impedir tela preta.</p><select value={fallbackId} onChange={e=>setFallbackId(e.target.value)} className="mt-3 w-full rounded-lg border p-2.5 text-sm"><option value="">Selecione uma identidade pronta</option>{identity.filter(x=>x.media_kind==='identity').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" disabled={busy||!fallbackId} onClick={async()=>{setBusy(true);try{await configureGsaTvFallback(fallbackId);toast.success('Tela de emergência preparada e ativada.');await onChanged()}catch(err:any){toast.error(err?.message||'Falha ao configurar emergência.')}finally{setBusy(false)}}} className="mt-2 w-full rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-bold text-indigo-800 disabled:opacity-50">Usar como emergência oficial</button></div>
    </section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-black">Camadas do sinal</h2>{graphics.length===0?<div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Nenhuma camada configurada.</div>:<div className="space-y-3">{graphics.map(g=><div key={g.id} className="flex items-center justify-between gap-4 rounded-xl border p-4"><div><div className="flex items-center gap-2"><strong>{g.name}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${g.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{g.enabled?'ativa':'inativa'}</span></div><p className="mt-1 text-xs text-slate-500">{g.layer_type}{g.text_content?` · ${g.text_content}`:''}</p></div><button disabled={busy} onClick={()=>void remove(g.id)} className="p-2 text-rose-600" aria-label="Excluir camada"><Trash2 className="h-4 w-4"/></button></div>)}</div>}</section>
  </div>;
}
