import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Building2, FileCheck2, HeartPulse, Loader2, MessageCircle, Plus, RefreshCw, Search, ShieldCheck, WalletCards, X } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { supabase } from '../../lib/supabase';
import { navigate } from '../../routing/navigationService';
import { routes } from '../../routing/routeCatalog';

type Domain = 'saude' | 'seguros';
type Props = { domain: Domain; initialTab?: string; initialItemId?: string };
type Tab = 'dashboard' | 'parceiros' | 'produtos' | 'cotacoes' | 'propostas' | 'contratos' | 'assessorias' | 'comissoes' | 'documentos' | 'assistencias' | 'sinistros' | 'atendimentos';

const definitions = {
  saude: { label: 'GSA Saúde', accent: '#159988', icon: HeartPulse, contract: 'Planos contratados', product: 'Planos', productTable: 'saude_produtos', contractTable: 'saude_contratos' },
  seguros: { label: 'GSA Seguros', accent: '#3569e8', icon: ShieldCheck, contract: 'Apólices', product: 'Ofertas', productTable: 'seguros_produtos', contractTable: 'seguros_apolices' },
} as const;

const labels: Record<Tab, string> = { dashboard: 'Visão geral', parceiros: 'Parceiros', produtos: 'Catálogo', cotacoes: 'Cotações', propostas: 'Propostas', contratos: 'Contratações', assessorias: 'Assessorias', comissoes: 'Comissões', documentos: 'Documentos', assistencias: 'Assistências', sinistros: 'Sinistros', atendimentos: 'Atendimentos' };

function tableFor(domain: Domain, tab: Tab) {
  const d = definitions[domain];
  const map: Record<Tab, string> = {
    dashboard: '', parceiros: `${domain}_parceiros`, produtos: d.productTable,
    cotacoes: `${domain}_cotacoes`, propostas: `${domain}_propostas`, contratos: d.contractTable,
    assessorias: `${domain}_assessorias`, comissoes: `${domain}_comissoes`, documentos: `${domain}_documentos`,
    assistencias: domain === 'seguros' ? 'seguros_assistencias' : 'saude_atendimentos',
    sinistros: domain === 'seguros' ? 'seguros_sinistros' : 'saude_atendimentos', atendimentos: `${domain}_atendimentos`,
  };
  return map[tab];
}

export function ProtectionAdminModule({ domain, initialTab = 'dashboard' }: Props) {
  const d = definitions[domain]; const Icon = d.icon;
  const normalizedTab = initialTab === 'apolices' ? 'contratos' : initialTab;
  const validTab = (Object.keys(labels) as Tab[]).includes(normalizedTab as Tab) ? normalizedTab as Tab : 'dashboard';
  const [tab, setTab] = useState<Tab>(validTab);
  const domainTabs: Tab[] = domain === 'seguros' ? ['dashboard','parceiros','produtos','cotacoes','propostas','contratos','assessorias','comissoes','assistencias','sinistros','documentos','atendimentos'] : ['dashboard','parceiros','produtos','cotacoes','propostas','contratos','assessorias','comissoes','documentos','atendimentos'];
  useEffect(() => setTab(validTab), [validTab]);
  const openTab = (key: Tab) => {
    setTab(key);
    const catalog = domain === 'saude' ? routes.admin.saude : routes.admin.seguros;
    const pathMap: Record<Tab, () => string> = { dashboard: catalog.dashboard, parceiros: catalog.parceiros, produtos: catalog.produtos, cotacoes: catalog.cotacoes, propostas: catalog.propostas, contratos: catalog.contratos, assessorias: catalog.assessorias, comissoes: catalog.comissoes, documentos: catalog.documentos, assistencias: catalog.assistencias, sinistros: catalog.sinistros, atendimentos: catalog.atendimentos };
    navigate(pathMap[key]());
  };
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="flex items-center gap-3 text-2xl font-black"><span className="flex h-11 w-11 items-center justify-center rounded-2xl text-white" style={{ background: d.accent }}><Icon className="h-6 w-6" /></span>{d.label}</h1><p className="mt-2 text-sm text-neutral-500">Gestão de parceiros, catálogo, cotações, propostas, contratos e receitas de comissão.</p></div></div><div className="flex gap-1 overflow-x-auto rounded-2xl border border-black/5 bg-white p-1.5 shadow-sm">{domainTabs.map(key => <button key={key} onClick={() => openTab(key)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab === key ? 'text-white shadow-sm' : 'text-neutral-500 hover:bg-neutral-50'}`} style={tab === key ? { background: d.accent } : undefined}>{labels[key]}</button>)}</div>{tab === 'dashboard' ? <Dashboard domain={domain} onOpen={openTab} /> : <DataManager domain={domain} tab={tab} />}</div>;
}

function Dashboard({ domain, onOpen }: { domain: Domain; onOpen: (tab: Tab) => void }) {
  const d = definitions[domain]; const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [counts, setCounts] = useState<Record<string, number>>({});
  const cards: { tab: Tab; label: string; icon: React.ElementType }[] = [{ tab: 'parceiros', label: 'Parceiros ativos', icon: Building2 }, { tab: 'produtos', label: `${d.product} publicados`, icon: FileCheck2 }, { tab: 'cotacoes', label: 'Cotações abertas', icon: Search }, { tab: 'propostas', label: 'Propostas aguardando', icon: WalletCards }, { tab: 'contratos', label: d.contract, icon: ShieldCheck }, { tab: 'atendimentos', label: 'Atendimentos abertos', icon: MessageCircle }];
  const load = async () => { setLoading(true); setError(''); try { const entries = await Promise.all(cards.map(async card => { let q = supabase.from(tableFor(domain, card.tab)).select('*', { count: 'exact', head: true }); if (card.tab === 'parceiros') q = q.eq('status', 'ativo'); if (card.tab === 'produtos') q = q.eq('status', 'publicado'); if (card.tab === 'cotacoes' || card.tab === 'atendimentos') q = q.not('status', 'in', '(encerrado,cancelado)'); const { count, error } = await q; if (error) throw error; return [card.tab, count || 0] as const; })); setCounts(Object.fromEntries(entries)); } catch (e: any) { setError(e.message || 'Falha ao consultar os indicadores.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [domain]);
  if (loading) return <PanelState icon={Loader2} text="Carregando indicadores reais..." spin />;
  if (error) return <PanelState icon={Activity} text={error} action={load} />;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(card => { const I = card.icon; return <button key={card.tab} onClick={() => onOpen(card.tab)} className="rounded-2xl border border-black/5 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl" style={{ color: d.accent, background: `${d.accent}12` }}><I className="h-5 w-5" /></span><strong className="text-3xl font-black">{counts[card.tab] || 0}</strong></div><p className="mt-5 font-bold text-neutral-600">{card.label}</p></button>; })}</div>;
}

function DataManager({ domain, tab }: { domain: Domain; tab: Exclude<Tab, 'dashboard'> }) {
  const d = definitions[domain]; const table = tableFor(domain, tab);
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<any>(null);
  const load = async () => { setLoading(true); setError(''); const { data, error } = await supabase.from(table).select('*').order('created_at', { ascending: false }).limit(250); if (error) setError(error.message); else setItems(data || []); setLoading(false); };
  useEffect(() => { void load(); }, [table]);
  const filtered = useMemo(() => items.filter(item => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())), [items, search]);
  const canCreate = tab === 'parceiros' || tab === 'produtos' || tab === 'propostas';
  const updateStatus = async (item: any, status: string) => { const { error } = await supabase.from(table).update({ status, updated_at: new Date().toISOString() }).eq('id', item.id); if (error) toast.error(error.message); else { toast.success('Status atualizado.'); void load(); } };
  return <div className="overflow-hidden rounded-2xl border border-black/5 bg-white shadow-sm"><div className="flex flex-col justify-between gap-4 border-b border-black/5 p-5 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">{labels[tab]}</h2><p className="text-sm text-neutral-500">{items.length} registro(s) encontrado(s)</p></div><div className="flex gap-2"><label className="flex items-center gap-2 rounded-xl border border-black/10 px-3"><Search className="h-4 w-4 text-neutral-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Pesquisar" className="w-40 bg-transparent py-2.5 text-sm outline-none" /></label><button onClick={load} className="rounded-xl border border-black/10 p-3" aria-label="Atualizar"><RefreshCw className="h-4 w-4" /></button>{canCreate && <button onClick={() => { setEditing(null); setModal(true); }} className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black text-white" style={{ background: d.accent }}><Plus className="h-4 w-4" /> Novo</button>}</div></div>{loading ? <PanelState icon={Loader2} text="Carregando registros..." spin /> : error ? <PanelState icon={Activity} text={error} action={load} /> : filtered.length === 0 ? <PanelState icon={Search} text={`Nenhum registro em ${labels[tab].toLowerCase()}.`} /> : <div className="divide-y divide-black/5">{filtered.map(item => <div key={item.id} className="flex flex-col justify-between gap-4 p-5 hover:bg-neutral-50 sm:flex-row sm:items-center"><div className="min-w-0"><p className="truncate font-black">{item.nome || item.titulo || item.protocolo || item.numero || `Registro ${String(item.id).slice(0, 8)}`}</p><p className="mt-1 truncate text-sm text-neutral-500">{item.resumo || item.email || item.assunto || item.categoria || (item.created_at && new Date(item.created_at).toLocaleDateString('pt-BR'))}</p></div><div className="flex items-center gap-2">{item.status && <select value={item.status} onChange={e => updateStatus(item, e.target.value)} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-bold"><option value={item.status}>{String(item.status).replaceAll('_', ' ')}</option>{statusOptions(tab).filter(x => x !== item.status).map(x => <option key={x} value={x}>{x.replaceAll('_', ' ')}</option>)}</select>}{(tab === 'parceiros' || tab === 'produtos') && <button onClick={() => { setEditing(item); setModal(true); }} className="rounded-xl border border-black/10 px-3 py-2 text-xs font-black">Editar</button>}</div></div>)}</div>}{modal && (tab === 'parceiros' || tab === 'produtos') && <EditModal domain={domain} tab={tab} item={editing} onClose={() => setModal(false)} onSaved={() => { setModal(false); void load(); }} />}{modal && tab === 'propostas' && <ProposalModal domain={domain} onClose={() => setModal(false)} onSaved={() => { setModal(false); void load(); }} />}</div>;
}

function statusOptions(tab: Tab) {
  const options: Partial<Record<Tab, string[]>> = {
    parceiros: ['ativo', 'inativo'], produtos: ['rascunho', 'publicado', 'pausado', 'arquivado'],
    cotacoes: ['recebida', 'em_analise', 'aguardando_dados', 'propostas_disponiveis', 'encerrada', 'cancelada'],
    propostas: ['rascunho', 'enviada', 'visualizada', 'aceita', 'recusada', 'expirada', 'cancelada'],
    contratos: ['em_implantacao', 'ativo', 'suspenso', 'encerrado', 'cancelado'],
    assessorias: ['oferecida', 'aceita', 'cobranca_pendente', 'paga', 'cancelada'],
    comissoes: ['prevista', 'confirmada', 'recebida', 'estornada', 'cancelada'],
    documentos: ['enviado', 'em_analise', 'aprovado', 'rejeitado'],
    assistencias: ['solicitada', 'encaminhada_seguradora', 'em_atendimento', 'concluida', 'cancelada'],
    sinistros: ['comunicado', 'documentacao_pendente', 'encaminhado_seguradora', 'em_analise', 'indenizado', 'negado', 'encerrado'],
    atendimentos: ['aberto', 'em_atendimento', 'aguardando_cliente', 'resolvido', 'encerrado'],
  };
  return options[tab] || [];
}

function EditModal({ domain, tab, item, onClose, onSaved }: { domain: Domain; tab: 'parceiros' | 'produtos'; item: any; onClose: () => void; onSaved: () => void }) {
  const d = definitions[domain]; const [saving, setSaving] = useState(false); const [partners, setPartners] = useState<any[]>([]); const [form, setForm] = useState<any>(item || (tab === 'parceiros' ? { nome: '', status: 'ativo', comissao_tipo: 'porcentagem' } : { nome: '', slug: '', categoria: domain === 'saude' ? 'individual-familiar' : 'auto', status: 'rascunho', destaque: false }));
  useEffect(() => { if (tab === 'produtos') supabase.from(`${domain}_parceiros`).select('id,nome').eq('status', 'ativo').order('nome').then(({ data }) => setPartners(data || [])); }, [domain, tab]);
  const save = async () => { if (!form.nome?.trim()) return toast.error('Informe o nome.'); setSaving(true); const payload = { ...form, slug: tab === 'produtos' ? (form.slug || form.nome).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') : undefined, updated_at: new Date().toISOString() }; if (!item) delete payload.id; const { error } = await supabase.from(tableFor(domain, tab)).upsert(payload); setSaving(false); if (error) toast.error(error.message); else { toast.success('Registro salvo.'); onSaved(); } };
  const field = (name: string, label: string, type = 'text') => <label className="block text-sm font-bold">{label}<input type={type} value={form[name] ?? ''} onChange={e => setForm({ ...form, [name]: type === 'number' ? Number(e.target.value) : e.target.value })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 outline-none focus:border-black/30" /></label>;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{item ? 'Editar' : 'Novo'} {tab === 'parceiros' ? 'parceiro' : d.product.slice(0, -1).toLowerCase()}</h2><button onClick={onClose} className="rounded-full p-2 hover:bg-neutral-100"><X className="h-5 w-5" /></button></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{field('nome', 'Nome *')}{tab === 'parceiros' ? <>{field('documento', 'CNPJ/registro')}{field('site', 'Site')}{field('contato', 'Contato')}{field('comissao_valor', 'Comissão acordada', 'number')}<label className="block text-sm font-bold sm:col-span-2">Observações<textarea value={form.observacoes || ''} onChange={e => setForm({ ...form, observacoes: e.target.value })} rows={4} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3" /></label></> : <><label className="block text-sm font-bold">Parceiro<select value={form.parceiro_id || ''} onChange={e => setForm({ ...form, parceiro_id: e.target.value || null })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3"><option value="">Selecione</option>{partners.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label>{field('categoria', 'Categoria')}{field('imagem_url', 'URL da imagem')}{field('preco_referencia', domain === 'saude' ? 'Mensalidade de referência' : 'Prêmio de referência', 'number')}<label className="block text-sm font-bold sm:col-span-2">Resumo<textarea value={form.resumo || ''} onChange={e => setForm({ ...form, resumo: e.target.value })} rows={4} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3" /></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={!!form.destaque} onChange={e => setForm({ ...form, destaque: e.target.checked })} /> Destacar no catálogo</label></>}</div><div className="mt-8 flex justify-end gap-3"><button onClick={onClose} className="rounded-full border border-black/10 px-6 py-3 font-bold">Cancelar</button><button disabled={saving} onClick={save} className="flex items-center gap-2 rounded-full px-7 py-3 font-black text-white disabled:opacity-50" style={{ background: d.accent }}>{saving && <Loader2 className="h-4 w-4 animate-spin" />} Salvar</button></div></div></div>;
}

function ProposalModal({ domain, onClose, onSaved }: { domain: Domain; onClose: () => void; onSaved: () => void }) {
  const d = definitions[domain]; const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [quotes, setQuotes] = useState<any[]>([]); const [partners, setPartners] = useState<any[]>([]); const [products, setProducts] = useState<any[]>([]); const [form, setForm] = useState<any>({ cotacao_id: '', parceiro_id: '', produto_id: '', titulo: '', valor: '', franquia: '', taxa_assessoria_gsa: 0, validade_dias: 5 });
  useEffect(() => { Promise.all([supabase.from(`${domain}_cotacoes`).select('id,cliente_id,protocolo,categoria,status').not('status', 'in', '(encerrada,cancelada)').order('created_at', { ascending: false }), supabase.from(`${domain}_parceiros`).select('id,nome').eq('status', 'ativo').order('nome'), supabase.from(d.productTable).select('id,nome,parceiro_id').eq('status', 'publicado').order('nome')]).then(([q, p, pr]) => { setQuotes(q.data || []); setPartners(p.data || []); setProducts(pr.data || []); setLoading(false); }); }, [domain]);
  const save = async () => { const quote = quotes.find(q => q.id === form.cotacao_id); if (!quote || !form.parceiro_id || !Number(form.valor)) return toast.error('Selecione cotação, parceiro e informe o valor.'); setSaving(true); const protocol = `${domain === 'saude' ? 'SAU' : 'SEG'}-PROP-${Date.now().toString(36).toUpperCase()}`; const common: any = { cotacao_id: quote.id, cliente_id: quote.cliente_id, parceiro_id: form.parceiro_id, produto_id: form.produto_id || null, protocolo: protocol, titulo: form.titulo || `Proposta ${protocol}`, taxa_assessoria_gsa: Number(form.taxa_assessoria_gsa) || 0, validade_ate: new Date(Date.now() + Number(form.validade_dias || 5) * 86400000).toISOString(), status: 'enviada' }; if (domain === 'saude') common.mensalidade_operadora = Number(form.valor); else { common.premio_seguradora = Number(form.valor); common.franquia = Number(form.franquia) || null; } const { error } = await supabase.from(`${domain}_propostas`).insert(common); if (!error) await supabase.from(`${domain}_cotacoes`).update({ status: 'propostas_disponiveis', updated_at: new Date().toISOString() }).eq('id', quote.id); setSaving(false); if (error) toast.error(error.message); else { toast.success('Proposta enviada ao cliente.'); onSaved(); } };
  const input = (name: string, label: string, type = 'text') => <label className="block text-sm font-bold">{label}<input type={type} value={form[name] ?? ''} onChange={e => setForm({ ...form, [name]: e.target.value })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3" /></label>;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-black">Nova proposta</h2><button onClick={onClose}><X className="h-5 w-5" /></button></div>{loading ? <PanelState icon={Loader2} text="Carregando dados..." spin /> : <div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Cotação<select value={form.cotacao_id} onChange={e => setForm({ ...form, cotacao_id: e.target.value })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3"><option value="">Selecione</option>{quotes.map(q => <option key={q.id} value={q.id}>{q.protocolo} · {q.categoria}</option>)}</select></label><label className="text-sm font-bold">Parceiro<select value={form.parceiro_id} onChange={e => setForm({ ...form, parceiro_id: e.target.value, produto_id: '' })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3"><option value="">Selecione</option>{partners.map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="text-sm font-bold">Produto<select value={form.produto_id} onChange={e => setForm({ ...form, produto_id: e.target.value })} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3"><option value="">Opcional</option>{products.filter(p => !form.parceiro_id || p.parceiro_id === form.parceiro_id).map(p => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label>{input('titulo', 'Título da proposta')}{input('valor', domain === 'saude' ? 'Mensalidade da operadora (R$)' : 'Prêmio da seguradora (R$)', 'number')}{domain === 'seguros' && input('franquia', 'Franquia (R$)', 'number')}{input('taxa_assessoria_gsa', 'Taxa de assessoria GSA (R$)', 'number')}{input('validade_dias', 'Validade (dias)', 'number')}<p className="rounded-xl bg-amber-50 p-3 text-xs font-semibold leading-5 text-amber-800 sm:col-span-2">O valor da {domain === 'saude' ? 'mensalidade' : 'prêmio'} pertence à parceira. Somente comissão e eventual taxa de assessoria aceita são receitas da GSA.</p></div>}<div className="mt-7 flex justify-end gap-3"><button onClick={onClose} className="rounded-full border border-black/10 px-6 py-3 font-bold">Cancelar</button><button disabled={saving || loading} onClick={save} className="rounded-full px-7 py-3 font-black text-white disabled:opacity-50" style={{ background: d.accent }}>{saving ? 'Salvando...' : 'Enviar proposta'}</button></div></div></div>;
}

function PanelState({ icon: Icon, text, spin, action }: { icon: React.ElementType; text: string; spin?: boolean; action?: () => void }) { return <div className="p-14 text-center"><Icon className={`mx-auto h-9 w-9 text-neutral-300 ${spin ? 'animate-spin' : ''}`} /><p className="mt-4 font-bold text-neutral-500">{text}</p>{action && <button onClick={action} className="mt-4 rounded-full bg-neutral-900 px-5 py-2 text-sm font-black text-white">Tentar novamente</button>}</div>; }
