import React,{useCallback,useEffect,useState}from'react';
import{Archive,Database,HardDrive,Loader2,RefreshCw,Video,Webhook}from'lucide-react';
import{toast}from'react-hot-toast';
import{getGsaTvOperations,getGsaTvStorageStatus,saveGsaTvAlertSettings}from'../../../lib/gsaTvOperations';
import{GsaTvProductionStatus}from'./GsaTvProductionStatus';
const errorText=(e:unknown)=>e instanceof Error?e.message:String((e as any)?.message||e);
const bytes=(n:number)=>{if(!Number.isFinite(n))return'—';const u=['B','KB','MB','GB','TB'];let v=n,i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${u[i]}`};
export function GsaTvOperations({channelId='ch-main',audit=[],refreshAudit}:{channelId?:string;audit?:any[];refreshAudit?:()=>Promise<void>}){
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[ops,setOps]=useState<any>({alerts:{},recordings:[],backups:[],ai_usage:[]}),[storage,setStorage]=useState<any>(null);
 const[alert,setAlert]=useState({enabled:true,whatsapp_number:'',min_severity:'warning',cooldown_minutes:10});
 const load=useCallback(async()=>{setLoading(true);try{const[o,s]=await Promise.all([getGsaTvOperations(),getGsaTvStorageStatus()]);setOps(o);setStorage(s);setAlert(x=>({...x,enabled:o.alerts?.enabled??true,min_severity:o.alerts?.min_severity||'warning',cooldown_minutes:o.alerts?.cooldown_minutes||10}))}catch(e){toast.error(errorText(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-indigo-600"/></div>;
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Operações e continuidade</h2><p className="text-sm text-slate-500">Capacidade, gravações, alertas e recuperação da GSA TV.</p></div><button onClick={()=>void Promise.allSettled([load(),refreshAudit?.()])} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Atualizar</button></div>
 <GsaTvProductionStatus audit={audit}/>
 <div className="grid gap-3 md:grid-cols-4"><Metric icon={HardDrive} label="Disco usado" value={`${storage?.used_percent??0}%`}/><Metric icon={Database} label="Livre na VPS" value={bytes(Number(storage?.free_bytes||0))}/><Metric icon={Archive} label="Projeção" value={storage?.projected_days_remaining==null?'Sem pressão':`${storage.projected_days_remaining} dias`}/><Metric icon={Video} label="Gravações" value={String(ops.recordings?.length||0)}/></div>
 <div className="grid gap-4 xl:grid-cols-2"><Panel title="Armazenamento local" icon={HardDrive}><div className="space-y-3"><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{width:`${Math.min(100,storage?.used_percent||0)}%`}}/></div><div className="grid grid-cols-3 gap-2 text-xs"><Stat label="Total" value={bytes(Number(storage?.total_bytes||0))}/><Stat label="Usado" value={bytes(Number(storage?.used_bytes||0))}/><Stat label="Livre" value={bytes(Number(storage?.free_bytes||0))}/></div><div className="divide-y">{(storage?.by_kind||[]).map((x:any)=><div key={x.media_kind} className="flex items-center justify-between py-2 text-sm"><span>{x.media_kind}</span><strong>{x.items} · {bytes(Number(x.bytes||0))}</strong></div>)}</div></div></Panel>
 <Panel title="Alertas WhatsApp via n8n" icon={Webhook}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await saveGsaTvAlertSettings({channel_id:channelId,...alert});toast.success('Configuração de alertas salva.');setAlert({...alert,whatsapp_number:''});await load()}catch(e){toast.error(errorText(e))}finally{setSaving(false)}}}><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={alert.enabled} onChange={e=>setAlert({...alert,enabled:e.target.checked})}/>Alertas automáticos ativados</label><Field label="Número WhatsApp"><input inputMode="tel" value={alert.whatsapp_number} onChange={e=>setAlert({...alert,whatsapp_number:e.target.value})} placeholder={ops.alerts?.whatsapp_configured?'Destino já protegido · digite só para substituir':'55DDDNUMERO'}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Severidade mínima"><select value={alert.min_severity} onChange={e=>setAlert({...alert,min_severity:e.target.value})}><option value="info">Informação</option><option value="warning">Aviso</option><option value="error">Erro</option><option value="critical">Crítico</option></select></Field><Field label="Cooldown (min)"><input  type="number" min="1" max="1440" value={alert.cooldown_minutes} inputMode="numeric"
onChange={(e) => setAlert({...alert,cooldown_minutes:Number(e.target.value)})}/></Field></div><p className="text-xs text-slate-500">O destino não é devolvido pelo servidor. O n8n existente usa a Evolution API interna para o envio.</p><button disabled={saving} className="w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">Salvar alertas</button></form></Panel></div>
 <div className="grid gap-4 xl:grid-cols-2"><Panel title="Backups e restauração" icon={Archive}>{ops.backups?.length?<div className="divide-y">{ops.backups.slice(0,12).map((x:any)=><div key={x.id} className="flex items-center justify-between gap-3 py-3"><div><strong className="text-sm">{x.backup_type}</strong><p className="text-xs text-slate-500">{new Date(x.started_at).toLocaleString('pt-BR')} · {x.size_bytes?bytes(Number(x.size_bytes)):''}</p></div><Badge value={x.state}/></div>)}</div>:<Empty text="O primeiro backup integral ainda não foi executado."/>}</Panel>
 <Panel title="Gravações de entradas ao vivo" icon={Video}>{ops.recordings?.length?<div className="divide-y">{ops.recordings.slice(0,12).map((x:any)=><div key={x.id} className="flex items-center justify-between gap-3 py-3"><div><strong className="text-sm">{x.metadata?.source_name||'Entrada ao vivo'}</strong><p className="text-xs text-slate-500">{new Date(x.started_at).toLocaleString('pt-BR')}{x.media_item_id?' · enviada para a biblioteca':''}</p></div><Badge value={x.state}/></div>)}</div>:<Empty text="Nenhuma entrada ao vivo foi gravada ainda."/>}</Panel></div>
 </div>;
}
function Panel({title,icon:Icon,children}:{title:string;icon:React.ElementType;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-black"><Icon className="h-5 w-5 text-indigo-600"/>{title}</h3>{children}</section>}
function Metric({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <div className="flex items-center gap-3 rounded-2xl border bg-white p-4"><div className="rounded-xl bg-indigo-50 p-2"><Icon className="h-5 w-5 text-indigo-700"/></div><div><p className="text-xs text-slate-500">{label}</p><strong>{value}</strong></div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-slate-500">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div>}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span>{React.cloneElement(children as React.ReactElement<any>,{className:'w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-indigo-500'})}</label>}
function Badge({value}:{value:string}){const good=['ready','verified','restored_test','completed','sent'].includes(value);return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${good?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{value}</span>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-7 text-center text-sm text-slate-500">{text}</div>}
export default GsaTvOperations;
