import React,{useCallback,useEffect,useMemo,useState}from'react';
import{BadgeDollarSign,Link2,Loader2,Pause,Play,Plus,RefreshCw,Unlink}from'lucide-react';
import{toast}from'react-hot-toast';
import{callAdminRpc}from'../../../lib/adminRpc';

type Data={campaigns:any[];assets:any[]};
const EMPTY:Data={campaigns:[],assets:[]};
const err=(e:unknown)=>e instanceof Error?e.message:String((e as any)?.message||e);
export function GsaTvAdvertisingStudio({channelId='ch-main',media=[]}:{channelId?:string;media?:any[]}){
 const[data,setData]=useState<Data>(EMPTY),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const[form,setForm]=useState({advertiser_name:'',name:'',starts_at:'',ends_at:'',contracted_runs:'',max_frequency_per_hour:'',priority:'50',competitor_group:''});
 const[link,setLink]=useState({campaign_id:'',media_item_id:'',weight:'1'});
 const load=useCallback(async()=>{setLoading(true);try{setData({...EMPTY,...await callAdminRpc<Data>('gsa_admin_gsa_tv_advertising_snapshot')})}catch(e){toast.error(err(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const mutate=async(action:string,payload:Record<string,unknown>,message:string)=>{setBusy(true);try{await callAdminRpc('gsa_admin_gsa_tv_advertising_mutate',{p_action:action,p_payload:{channel_id:channelId,...payload}});toast.success(message);await load()}catch(e){toast.error(err(e))}finally{setBusy(false)}};
 const eligible=useMemo(()=>media.filter(x=>x.media_kind==='advertising'&&(x.state==='ready'||x.approval_state==='approved')&&x.approval_state!=='rejected'),[media]);
 if(loading)return <div className="flex min-h-40 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>;
 return <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Gestão de campanhas</h2><p className="text-sm text-slate-500">Contrato de inserções, prioridade, frequência e peças autorizadas.</p></div><button onClick={()=>void load()} className="rounded-lg border p-2"><RefreshCw className="h-4 w-4"/></button></div> <div className="grid gap-4 xl:grid-cols-[400px_1fr]"><Card title="Nova campanha"><form className="grid gap-3" onSubmit={async e=>{e.preventDefault();await mutate('save_campaign',{...form,starts_at:new Date(form.starts_at).toISOString(),ends_at:new Date(form.ends_at).toISOString(),contracted_runs:form.contracted_runs||null,max_frequency_per_hour:form.max_frequency_per_hour||null,priority:Number(form.priority),status:'draft'},'Campanha criada.');setForm({...form,advertiser_name:'',name:'',contracted_runs:'',competitor_group:''})}}>
  <Field label="Anunciante"><input required value={form.advertiser_name} onChange={e=>setForm({...form,advertiser_name:e.target.value})}/></Field><Field label="Campanha"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>
  <div className="grid grid-cols-2 gap-2"><Field label="Início"><input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></Field><Field label="Fim"><input required type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></Field></div>
  <div className="grid grid-cols-2 gap-2"><Field label="Inserções contratadas"><input  type="number" min="1" value={form.contracted_runs} inputMode="numeric"
onChange={(e) => setForm({...form,contracted_runs:e.target.value})}/></Field><Field label="Máx./hora"><input  type="number" min="1" value={form.max_frequency_per_hour} inputMode="numeric"
onChange={(e) => setForm({...form,max_frequency_per_hour:e.target.value})}/></Field></div>
  <div className="grid grid-cols-2 gap-2"><Field label="Prioridade"><input  type="number" min="0" max="100" value={form.priority} inputMode="numeric"
onChange={(e) => setForm({...form,priority:e.target.value})}/></Field><Field label="Grupo concorrente"><input value={form.competitor_group} onChange={e=>setForm({...form,competitor_group:e.target.value})}/></Field></div>
  <button disabled={busy} className="flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Criar campanha</button></form></Card>
  <Card title="Campanhas"><div className="space-y-3">{data.campaigns.length?data.campaigns.map(c=><article key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{c.name}</strong><p className="text-xs text-slate-500">{c.advertiser_name} · {c.completed_runs||0}/{c.contracted_runs||'∞'} inserções</p></div><Badge value={c.status}/></div><div className="mt-3 flex gap-2">{c.status!=='active'?<button disabled={busy} onClick={()=>void mutate('set_campaign_state',{id:c.id,status:'active'},'Campanha ativada.')} className="flex items-center gap-1 rounded-lg border px-3 py-1.5 text-xs font-bold"><Play className="h-3.5 w-3.5"/>Ativar</button>:<button disabled={busy} onClick={()=>void mutate('set_campaign_state',{id:c.id,status:'paused'},'Campanha pausada.')} className="flex items-center gap-1 rounded-lg border px-3 py-1.5 text-xs font-bold"><Pause className="h-3.5 w-3.5"/>Pausar</button>}</div></article>):<Empty text="Nenhuma campanha cadastrada."/>}</div></Card></div> <Card title="Vincular peças às campanhas"><form className="grid gap-3 md:grid-cols-4" onSubmit={async e=>{e.preventDefault();await mutate('link_asset',{campaign_id:link.campaign_id,media_item_id:link.media_item_id,weight:Number(link.weight)},'Peça vinculada.')}}><Field label="Campanha"><select required value={link.campaign_id} onChange={e=>setLink({...link,campaign_id:e.target.value})}><option value="">Selecione</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Peça aprovada"><select required value={link.media_item_id} onChange={e=>setLink({...link,media_item_id:e.target.value})}><option value="">Selecione</option>{eligible.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></Field><Field label="Peso"><input  required type="number" min="1" value={link.weight} inputMode="numeric"
onChange={(e) => setLink({...link,weight:e.target.value})}/></Field><button disabled={busy} className="self-end rounded-lg bg-indigo-700 px-3 py-2.5 text-sm font-black text-white"><Link2 className="mr-1 inline h-4 w-4"/>Vincular</button></form>
 <div className="mt-4 divide-y">{data.assets.map(a=><div key={`${a.campaign_id}:${a.media_item_id}`} className="flex items-center justify-between gap-3 py-3"><div><strong className="text-sm">{a.title}</strong><p className="text-xs text-slate-500">Campanha: {data.campaigns.find(c=>c.id===a.campaign_id)?.name||a.campaign_id} · peso {a.weight}</p></div><button disabled={busy} onClick={()=>void mutate('unlink_asset',{campaign_id:a.campaign_id,media_item_id:a.media_item_id},'Peça desvinculada.')} className="p-2 text-rose-600"><Unlink className="h-4 w-4"/></button></div>)}</div></Card></section>;
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-black"><BadgeDollarSign className="h-5 w-5 text-indigo-600"/>{title}</h3>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span>{React.cloneElement(children as React.ReactElement<any>,{className:'w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-indigo-500'})}</label>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-[10px] font-black uppercase text-indigo-700">{value}</span>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-7 text-center text-sm text-slate-500">{text}</div>}
export default GsaTvAdvertisingStudio;
