\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE public.system_settings (
  key text PRIMARY KEY,
  value text
);

CREATE TABLE public.indicacoes (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  whatsapp_indicado text,
  status text,
  data_criacao timestamptz DEFAULT now(),
  data_cadastro_indicado timestamptz,
  data_indicacao date DEFAULT current_date,
  indicador_id uuid,
  indicado_nome text,
  voucher_id uuid
);

CREATE TABLE public.clientes (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  codigo_cliente text,
  nome text,
  email text,
  cpf text UNIQUE,
  cnpj text UNIQUE,
  tipo_pessoa text,
  telefone text UNIQUE,
  cep text,
  endereco text,
  numero text,
  bairro text,
  cidade text,
  estado text,
  observacoes text,
  status text,
  carteira_bloqueada boolean,
  pontos_bloqueados boolean,
  cadastro_aprovado boolean,
  bonus_boas_vindas_pendente boolean,
  indicacao_origem_id uuid,
  data_cadastro timestamptz
);

CREATE TABLE public.vouchers (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  cliente_id uuid
);

CREATE TABLE public.prestadores (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  tipo_cadastro text,
  nome_razao text,
  nome_responsavel text,
  documento text UNIQUE,
  email text,
  telefone text,
  cep text,
  numero text,
  area_servico text,
  observacoes text,
  status text
);

CREATE TABLE public.notificacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id uuid,
  titulo text,
  mensagem text,
  modulo text,
  tab text,
  item_id text,
  tipo text,
  destinatario_tipo text,
  prioridade text,
  acao_origem text,
  contexto jsonb
);

CREATE TABLE public.orcamentos (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  cliente_id uuid,
  codigo_orcamento text,
  status text,
  categoria text,
  data_criacao date,
  titulo_solicitacao text,
  descricao_solicitacao text,
  nivel_prioridade text,
  observacoes_servico text,
  total numeric,
  valor_servico numeric,
  quantidade integer,
  origem_gsa_store boolean,
  contato_publico jsonb,
  public_request_hash text UNIQUE
);

CREATE OR REPLACE FUNCTION public.gsa_assert_public_rate_limit(text, text, integer, interval)
RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;

CREATE OR REPLACE FUNCTION public.gsa_is_valid_cpf(text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT true; $$;

CREATE OR REPLACE FUNCTION public.gsa_is_valid_cnpj(text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT true; $$;

CREATE OR REPLACE FUNCTION public.gsa_generate_code(text)
RETURNS text LANGUAGE sql AS $$ SELECT $1 || '-TESTE'; $$;

CREATE OR REPLACE FUNCTION public.gsa_apply_points_internal(uuid, integer, text, text, uuid, boolean)
RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;

INSERT INTO public.system_settings(key, value) VALUES
  ('codigo_cadastro_padrao_ativo', 'true'),
  ('codigo_cadastro_padrao', 'TESTE-HOME'),
  ('indicado_recompensa_tipo', 'desconto'),
  ('indicado_valor_pontos', '0');

INSERT INTO public.indicacoes(whatsapp_indicado, status, indicado_nome)
VALUES ('11999999999', 'aberta', 'Dado que não pode ser exposto');

\i supabase/migrations/20260720215500_fix_public_home_contracts.sql
\i supabase/migrations/20260720215530_minimize_public_referral_lookup.sql
\i supabase/migrations/20260720215600_guard_legacy_budget_permissions.sql

DO $tests$
DECLARE
  v_default jsonb;
  v_referral jsonb;
  v_budget jsonb;
  v_client jsonb;
BEGIN
  v_default := public.gsa_public_lookup_referral('TESTE-HOME');
  IF v_default <> jsonb_build_object('valid', true, 'kind', 'default') THEN
    RAISE EXCEPTION 'Resposta inesperada para código público: %', v_default;
  END IF;

  v_referral := public.gsa_public_lookup_referral('11999999999');
  IF v_referral <> jsonb_build_object('valid', true, 'kind', 'referral') THEN
    RAISE EXCEPTION 'Resposta pública de indicação expõe dados ou está incorreta: %', v_referral;
  END IF;

  v_budget := public.gsa_public_create_enterprise_budget(jsonb_build_object(
    'nome', 'Cliente de Teste',
    'email', 'teste@example.invalid',
    'telefone', '11988887777',
    'tipo', 'site',
    'solicitacao', 'Preciso de um site institucional completo para minha empresa.'
  ));
  IF NOT coalesce((v_budget->>'success')::boolean, false) THEN
    RAISE EXCEPTION 'Orçamento público não foi criado: %', v_budget;
  END IF;

  v_client := public.gsa_public_register_client(
    'TESTE-HOME',
    jsonb_build_object(
      'tipo_pessoa', 'pf',
      'nome', 'Cliente Teste Home',
      'email', 'cliente@example.invalid',
      'telefone', '11977776666',
      'cep', '01001000',
      'numero', '10',
      'endereco', 'Praça da Sé',
      'bairro', 'Sé',
      'cidade', 'São Paulo',
      'estado', 'SP',
      'cpf', '12345678909'
    )
  );
  IF NOT coalesce((v_client->>'success')::boolean, false) THEN
    RAISE EXCEPTION 'Cadastro público não foi criado: %', v_client;
  END IF;

  IF NOT has_function_privilege('anon', 'public.gsa_public_create_enterprise_budget(jsonb)', 'EXECUTE') THEN
    RAISE EXCEPTION 'Compatibilidade do orçamento atual deveria estar ativa sem a função v2.';
  END IF;
END;
$tests$;

CREATE OR REPLACE FUNCTION public.gsa_public_create_enterprise_budget_v2(jsonb)
RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object('success', true); $$;

\i supabase/migrations/20260720215600_guard_legacy_budget_permissions.sql

DO $permission_tests$
BEGIN
  IF has_function_privilege('anon', 'public.gsa_public_create_enterprise_budget(jsonb)', 'EXECUTE')
     OR has_function_privilege('authenticated', 'public.gsa_public_create_enterprise_budget(jsonb)', 'EXECUTE') THEN
    RAISE EXCEPTION 'A função legada foi reaberta mesmo com a rotina v2 presente.';
  END IF;

  IF NOT has_function_privilege('service_role', 'public.gsa_public_create_enterprise_budget(jsonb)', 'EXECUTE') THEN
    RAISE EXCEPTION 'O backend perdeu acesso à função legada.';
  END IF;
END;
$permission_tests$;
