import fs from 'node:fs';
const root = 'C:/Users/Adriano Farias/Downloads/remix-9.10_-grupo-gsa---gestão-de-serviços - Copia (4)';
function replaceOnce(path, oldText, newText, label) {
  const original = fs.readFileSync(path, 'utf8');
  const crlf = original.includes('\r\n');
  let text = original.replace(/\r\n/g, '\n');
  const count = text.split(oldText).length - 1;
  if (count !== 1) throw new Error(`${label}: esperado 1, encontrado ${count}`);
  text = text.replace(oldText, newText);
  fs.writeFileSync(path, crlf ? text.replace(/\n/g, '\r\n') : text, 'utf8');
}
const legacy = `${root}/src/components/admin/ConfiguracoesModule.tsx`;
replaceOnce(legacy,
  "    {activeTab === 'financeiro' && <section className=\"space-y-6\"><CalculatorProPaymentConfiguration />\n      <Card title=\"Desconto PIX\" icon={Wallet}>",
  "    {activeTab === 'financeiro' && <section className=\"space-y-6\"><CalculatorProPaymentConfiguration />\n      <Card title=\"Taxa de Saque do Crédito GSA\" icon={Wallet}>\n        <div className=\"grid gap-4 sm:grid-cols-2\"><SelectField label=\"Tipo da taxa\" value={value('credito_saque_taxa_tipo', 'percentual')} onChange={(next) => setValue('credito_saque_taxa_tipo', next)} options={[[\"percentual\", \"Percentual sobre o saque\"], [\"fixa\", \"Valor fixo por saque\"]]} /><NumberField label={value('credito_saque_taxa_tipo', 'percentual') === 'percentual' ? 'Taxa (%)' : 'Taxa fixa (R$)'} value={value('credito_saque_taxa_valor', '0')} onChange={(next) => setValue('credito_saque_taxa_valor', next)} /></div>\n        <p className=\"mt-4 rounded-xl border border-indigo-100 bg-indigo-50 p-3 text-xs text-indigo-900\">O cliente vê o valor do saque + taxa antes de confirmar. A configuração usada fica congelada no protocolo e a fatura vence 30 dias após a liberação PIX.</p>\n        <SaveButton saving={saving} onClick={() => void saveSettings(['credito_saque_taxa_tipo', 'credito_saque_taxa_valor'], 'Taxa de saque do crédito salva.')} />\n      </Card>\n      <Card title=\"Desconto PIX\" icon={Wallet}>",
  'legacy finance card');
const gov = `${root}/src/components/admin/super-domains/governanca/GovernancaConfiguracoesView.tsx`;
replaceOnce(gov,
  "          <CalculatorProPaymentConfiguration />\n\n          {/* Regras de Desconto PIX */}",
  "          <CalculatorProPaymentConfiguration />\n\n          <div className=\"bg-white p-6 rounded-xl border border-slate-200 shadow-xs space-y-4\">\n            <div className=\"flex items-center gap-3 border-b border-slate-100 pb-4\"><span className=\"p-2 rounded-lg bg-indigo-50 text-indigo-600 border border-indigo-100\"><Wallet className=\"h-5 w-5\" /></span><div><h3 className=\"text-sm font-bold text-slate-900\">Taxa de Saque do Crédito GSA</h3><p className=\"text-xs text-slate-500\">Taxa pré-configurada exibida ao cliente antes da solicitação</p></div></div>\n            <div className=\"grid gap-4 sm:grid-cols-2\"><div><label className=\"block text-xs font-bold text-slate-700 mb-1\">Tipo da taxa</label><select value={value('credito_saque_taxa_tipo', 'percentual')} onChange={(e) => setValue('credito_saque_taxa_tipo', e.target.value)} className=\"w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-xs font-medium\"><option value=\"percentual\">Percentual sobre o saque</option><option value=\"fixa\">Valor fixo por saque</option></select></div><div><label className=\"block text-xs font-bold text-slate-700 mb-1\">{value('credito_saque_taxa_tipo', 'percentual') === 'percentual' ? 'Taxa (%)' : 'Taxa fixa (R$)'}</label><input type=\"number\" min=\"0\" max={value('credito_saque_taxa_tipo', 'percentual') === 'percentual' ? 100 : undefined} value={value('credito_saque_taxa_valor', '0')} onChange={(e) => setValue('credito_saque_taxa_valor', e.target.value)} className=\"w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-xs font-medium font-mono\" /></div></div>\n            <div className=\"rounded-xl border border-indigo-100 bg-indigo-50 p-3 text-[11px] leading-relaxed text-indigo-900\">O valor calculado é exibido antes da confirmação e fica registrado no protocolo. Alterações futuras da taxa não modificam solicitações já abertas.</div>\n            <div className=\"flex justify-end\"><button type=\"button\" disabled={saving} onClick={() => void saveSettings(['credito_saque_taxa_tipo', 'credito_saque_taxa_valor'], 'Taxa de saque do crédito salva.')} className=\"px-4 py-2 text-xs font-bold rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-50 flex items-center gap-1.5\"><Save className=\"h-3.5 w-3.5\" />{saving ? 'Salvando...' : 'Salvar Taxa de Saque'}</button></div>\n          </div>\n\n          {/* Regras de Desconto PIX */}",
  'governanca finance card');
console.log('SETTINGS_PATCH_OK');
