import fs from 'node:fs';
const file='src/components/admin/FornecedoresModule.tsx'; let s=fs.readFileSync(file,'utf8');
const rep=(re,v,l)=>{const b=s;s=s.replace(re,v);if(s===b)throw new Error(`Patch ausente: ${l}`)};
rep(/  getAdminSupplierSnapshot,\r?\n/, '  getAdminSupplierSnapshot,\n  getAdminSupplierFinancialAnomalies,\n', 'import-anomalies');
rep(/  reviewAdminSupplierDelivery,\r?\n/, '  reviewAdminSupplierDelivery,\n  reviewAdminSupplierBankChange,\n', 'import-bank-review');
rep(/  const \[reason, setReason\] = useState\(''\);/, "  const [reason, setReason] = useState('');\n  const [bankReason, setBankReason] = useState('');\n  const [financialAnomalies, setFinancialAnomalies] = useState<Array<Record<string, any>>>([]);", 'admin-state');
rep(/try \{\r?\n\s*setSnapshot\(await getAdminSupplierSnapshot\(\)\);\r?\n\s*\} catch/, `try {\n      const [nextSnapshot, anomalies] = await Promise.all([\n        getAdminSupplierSnapshot(),\n        getAdminSupplierFinancialAnomalies(),\n      ]);\n      setSnapshot(nextSnapshot);\n      setFinancialAnomalies(anomalies || []);\n    } catch`, 'admin-load');
rep(/  const openProductReview = \(request: any, action: ProductAction\) => \{/, `  const reviewBankChange = async (approve: boolean) => {\n    if (!approval) return;\n    if (!approve && bankReason.trim().length < 3) return toast.error('Informe o motivo da recusa.');\n    setSaving(true);\n    try {\n      await reviewAdminSupplierBankChange(approval.id, approve, bankReason);\n      toast.success(approve ? 'Dados bancários aprovados.' : 'Alteração bancária recusada.');\n      setBankReason('');\n      setApproval(null);\n      await load();\n    } catch (error: any) { toast.error(error?.message || 'Não foi possível revisar os dados bancários.'); }\n    finally { setSaving(false); }\n  };\n\n  const openProductReview = (request: any, action: ProductAction) => {`, 'bank-review-handler');
fs.writeFileSync(file,s,'utf8'); console.log('SUPPLIER_ADMIN_BASE_PATCH_OK');
