from pathlib import Path
p=Path(r'supabase/functions/gsa-auth-session/index.ts')
s=p.read_text(encoding='utf-8')
def once(old,new,label):
    global s
    if s.count(old)!=1: raise RuntimeError(f'{label}: {s.count(old)}')
    s=s.replace(old,new,1)

once("  submit_partner_appeal: {\n    ip: { limit: 15, windowSeconds: 900, blockSeconds: 3600 },\n    subject: { limit: 5, windowSeconds: 900, blockSeconds: 3600 },\n  },\n};", "  submit_partner_appeal: {\n    ip: { limit: 15, windowSeconds: 900, blockSeconds: 3600 },\n    subject: { limit: 5, windowSeconds: 900, blockSeconds: 3600 },\n  },\n  request_provider_registration_code: {\n    ip: { limit: 8, windowSeconds: 900, blockSeconds: 3600 },\n    subject: { limit: 3, windowSeconds: 900, blockSeconds: 1800 },\n  },\n  verify_provider_registration_code: {\n    ip: { limit: 15, windowSeconds: 900, blockSeconds: 3600 },\n    subject: { limit: 6, windowSeconds: 900, blockSeconds: 3600 },\n  },\n};",'limits')

anchor="  if (action === 'login_pin') {"
provider_norm="  if (action === 'request_provider_registration_code') {\n    const telefone = digits(payload.telefone);\n    if (![10, 11].includes(telefone.length)) return null;\n    return { telefone };\n  }\n\n  if (action === 'verify_provider_registration_code') {\n    const challengeId = text(payload.challenge_id, 36).toLowerCase();\n    const telefone = digits(payload.telefone);\n    const code = digits(payload.code);\n    const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;\n    if (!uuidPattern.test(challengeId) || ![10, 11].includes(telefone.length) || code.length !== 6) return null;\n    return { challenge_id: challengeId, telefone, code };\n  }\n\n"
once(anchor,provider_norm+anchor,'normalize')once("function subjectFor(action: AuthAction, payload: Record<string, string>) {\n  if (action === 'login_admin' || action === 'login_colaborador') return payload.code;\n  return payload.documento || payload.challenge_id || payload.protocol;\n}", "function subjectFor(action: AuthAction, payload: Record<string, string>) {\n  if (action === 'login_admin' || action === 'login_colaborador') return payload.code;\n  if (action === 'request_provider_registration_code') return payload.telefone;\n  return payload.documento || payload.challenge_id || payload.protocol || payload.telefone;\n}",'subject')

once("      || action === 'complete_client_first_access'\n    ? 'before'", "      || action === 'complete_client_first_access'\n      || action === 'request_provider_registration_code'\n      || action === 'verify_provider_registration_code'\n    ? 'before'",'rate-mode')

once("      'complete_client_recovery',\n    ]);", "      'complete_client_recovery',\n      'request_provider_registration_code',\n      'verify_provider_registration_code',\n    ]);",'supported')

handler_anchor="    if (body.action === 'request_partner_appeal') {"
handler="    if (body.action === 'request_provider_registration_code') {\n      const challengeId = crypto.randomUUID();\n      const code = String(crypto.getRandomValues(new Uint32Array(1))[0] % 1_000_000).padStart(6, '0');\n      const codeHash = await hashBucket(serviceRoleKey, `provider-registration:${challengeId}`, code);\n      const { error: challengeError } = await admin.from('gsa_provider_registration_challenges').insert({\n        id: challengeId, telefone: normalizedPayload.telefone, code_hash: codeHash, expires_at: new Date(Date.now() + 300_000).toISOString(),\n      });\n      if (challengeError) { console.error('Falha ao criar desafio do prestador.', challengeError); return json({ error: 'verification_unavailable' }, 503, allowedOrigin); }\n      const delivery = await sendWhatsAppMessage(normalizedPayload.telefone, `Seu código de confirmação para o cadastro de prestador no GSA HUB é: *${code}*\\n\\nEle expira em 5 minutos. Não compartilhe este código.`);\n      if (!delivery.success) {\n        await admin.from('gsa_provider_registration_challenges').delete().eq('id', challengeId);\n        return json({ error: 'verification_delivery_failed' }, 503, allowedOrigin);\n      }\n      const phoneDigits = digits(normalizedPayload.telefone);\n      return json({ success: true, challenge_id: challengeId, expires_in: 300, destination: `••••${phoneDigits.slice(-4)}` }, 200, allowedOrigin);\n    }\n\n    if (body.action === 'verify_provider_registration_code') {\n      const codeHash = await hashBucket(serviceRoleKey, `provider-registration:${normalizedPayload.challenge_id}`, normalizedPayload.code);\n      const { data: verification, error: verificationError } = await admin.rpc('gsa_verify_provider_registration_challenge', {\n        p_challenge_id: normalizedPayload.challenge_id, p_telefone: normalizedPayload.telefone, p_code_hash: codeHash,\n      });\n      if (verificationError) { console.error('Falha ao validar WhatsApp do prestador.', verificationError); return json({ error: 'verification_unavailable' }, 503, allowedOrigin); }\n      if (!verification?.success) return json(verification || { success: false, error: 'invalid_code' }, verification?.error === 'too_many_attempts' ? 429 : 400, allowedOrigin);\n      await clearSubjectRateLimit(admin, subjectBucket);\n      return json(verification, 200, allowedOrigin);\n    }\n\n"
once(handler_anchor,handler+handler_anchor,'handlers')
p.write_text(s,encoding='utf-8')
print('provider gateway patched')