import fs from 'node:fs';
const p='src/components/admin/ProdutosModule.tsx';
let s=fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n');
s=s.replace("import { getAdminProductSupplierConfig, upsertAdminProductSupplierConfig, setAdminProductDiscount } from '../../lib/adminRpc';", "import { callAdminRpc, getAdminProductSupplierConfig, upsertAdminProductSupplierConfig, setAdminProductDiscount } from '../../lib/adminRpc';");
function rep(old,neu,label){const n=s.split(old).length-1;if(n!==1)throw new Error(`${label}: ${n}`);s=s.replace(old,neu);}
rep(`const { error } = await supabase.from('produtos').update({ \n                              tipo_cliente: next,\n                              descricao: \`${'${selectedProduto.descricao || \'\'} ${auditTag}'}\`.trim()\n                            }).eq('id', selectedProduto.id);\n                            if (error) throw error;`, `await callAdminRpc('gsa_admin_patch_marketplace_product', {\n                              p_produto_id: selectedProduto.id,\n                              p_patch: { tipo_cliente: next, descricao: \`${'${selectedProduto.descricao || \'\'} ${auditTag}'}\`.trim() },\n                            });`, 'tipo cliente');
function rrep(re,neu,label){const m=[...s.matchAll(new RegExp(re.source,re.flags.includes('g')?re.flags:re.flags+'g'))];if(m.length!==1)throw new Error(`${label}: ${m.length}`);s=s.replace(re,neu);}
rrep(/const \{ error \} = await supabase\.from\('produtos'\)\.update\(\{ \n\s+categoria_id: catId \|\| null,\n\s+categoria: catNome \|\| null,\n\s+descricao: `\$\{selectedProduto\.descricao \|\| ''\} \$\{auditTag\}`\.trim\(\)\n\s+\}\)\.eq\('id', selectedProduto\.id\);\n\s+if \(error\) throw error;/, `await callAdminRpc('gsa_admin_patch_marketplace_product', {\n                          p_produto_id: selectedProduto.id,\n                          p_patch: { categoria_id: catId || null, categoria: catNome || null, descricao: \`${'${selectedProduto.descricao || \'\'} ${auditTag}'}\`.trim() },\n                        });`, 'categoria');
rrep(/const \{ error \} = await supabase\.from\('produtos'\)\.update\(\{ \n\s+ocultar_valor: newOcultar,\n\s+descricao: `\$\{selectedProduto\.descricao \|\| ''\} \$\{auditTag\}`\.trim\(\)\n\s+\}\)\.eq\('id', selectedProduto\.id\);\n\s+if \(error\) throw error;/, `await callAdminRpc('gsa_admin_patch_marketplace_product', {\n                            p_produto_id: selectedProduto.id,\n                            p_patch: { ocultar_valor: newOcultar, descricao: \`${'${selectedProduto.descricao || \'\'} ${auditTag}'}\`.trim() },\n                          });`, 'ocultar');
rep("const { error } = await supabase.from('produtos').update({ visivel_na_loja: val }).eq('id', selectedProduto.id);\n                            if (error) throw error;", "await callAdminRpc('gsa_admin_patch_marketplace_product', { p_produto_id: selectedProduto.id, p_patch: { visivel_na_loja: val } });", 'visivel');
rep("const { error } = await supabase.from('produtos').update({ controle_estoque: val }).eq('id', selectedProduto.id);\n                            if (error) throw error;", "await callAdminRpc('gsa_admin_patch_marketplace_product', { p_produto_id: selectedProduto.id, p_patch: { controle_estoque: val } });", 'estoque');
rrep(/const \{ error \} = await supabase\.from\('produtos'\)\.update\(\{ \n\s+status: newStatus,\n\s+descricao: `\$\{selectedProduto\.descricao \|\| ''\} \$\{auditTag\}`\.trim\(\)\n\s+\}\)\.eq\('id', selectedProduto\.id\);\n\s+if \(error\) throw error;/, `await callAdminRpc('gsa_admin_patch_marketplace_product', {\n                            p_produto_id: selectedProduto.id,\n                            p_patch: { status: newStatus, descricao: \`${'${selectedProduto.descricao || \'\'} ${auditTag}'}\`.trim() },\n                          });`, 'status');
fs.writeFileSync(p,s,'utf8');
console.log('PRODUTOS_MODULE_PATCHED');
