import fs from 'node:fs';
const p = String.raw`C:\Users\Adriano Farias\Downloads\remix-9.10_-grupo-gsa---gestão-de-serviços - Copia (4)\src\pages\AdvertiserPortal.tsx`;
let s = fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
const oldStart = `function FinanceSection({ campaigns }: { campaigns: AdvertisingCampaign[] }) {\n  const payable = campaigns.filter((campaign) => campaign.payment);`;
const newStart = `function FinanceSection({ campaigns }: { campaigns: AdvertisingCampaign[] }) {\n  const [creatingCheckoutId, setCreatingCheckoutId] = useState<string | null>(null);\n  const createCheckout = async (paymentId: string) => {\n    setCreatingCheckoutId(paymentId);\n    try {\n      const { data, error } = await supabase.functions.invoke<{ success?: boolean; checkout_url?: string }>('gsa-ads-public', { body: { action: 'create_checkout', payment_id: paymentId } });\n      if (error || !data?.success || !data.checkout_url) throw error || new Error('Checkout indisponível.');\n      const checkout = new URL(data.checkout_url);\n      if (checkout.protocol !== 'https:') throw new Error('URL de pagamento inválida.');\n      window.open(checkout.href, '_blank', 'noopener,noreferrer');\n      toast.success('Pagamento seguro aberto em uma nova aba.');\n    } catch (error) {\n      toast.error(message(error, 'Não foi possível gerar o pagamento agora.'));\n    } finally {\n      setCreatingCheckoutId(null);\n    }\n  };\n  const payable = campaigns.filter((campaign) => campaign.payment);`;
if (!s.includes('const [creatingCheckoutId')) { if (!s.includes(oldStart)) throw new Error('finance start missing'); s = s.replace(oldStart, newStart); }
s = s.replace("            {(payment.checkout_url || payment.pix_code) && payment.status !== 'paid' && (", "            {!['paid', 'refunded', 'cancelled'].includes(payment.status) && (");
const oldButton = `                  {payment.checkout_url && (\n                    <a href={payment.checkout_url} target="_blank" rel="noopener noreferrer" className="adv-btn-primary justify-center">\n                      <CreditCard className="h-4 w-4" /> Abrir pagamento\n                    </a>\n                  )}`;
const newButton = `                  {payment.checkout_url ? (\n                    <a href={payment.checkout_url} target="_blank" rel="noopener noreferrer" className="adv-btn-primary justify-center">\n                      <CreditCard className="h-4 w-4" /> Abrir pagamento\n                    </a>\n                  ) : (\n                    <button type="button" disabled={creatingCheckoutId === payment.id} onClick={() => void createCheckout(payment.id)} className="adv-btn-primary justify-center disabled:cursor-not-allowed disabled:opacity-60">\n                      <CreditCard className="h-4 w-4" /> {creatingCheckoutId === payment.id ? 'Gerando...' : 'Gerar pagamento seguro'}\n                    </button>\n                  )}`;
if (!s.includes("Gerar pagamento seguro")) { if (!s.includes(oldButton)) throw new Error('finance payment button missing'); s = s.replace(oldButton, newButton); }
fs.writeFileSync(p, s, 'utf8');
console.log('finance patched');
