
export const routes = {
  // Rotas Públicas
  public: {
    home: () => '/',
    services: () => '/servicos-e-assinaturas',
    freeTools: () => '/servicos-gratuitos',
    systems: () => '/criacao-de-site-e-sistemas',
    partners: () => '/parceiros',
    partner: (slug: string) => `/parceiros/${slug}`,
    ads: () => '/anuncios',
    advertise: () => '/anuncie',
    affiliates: () => '/afiliados',
    affiliateDashboard: () => '/afiliados/dashboard',
    affiliateLinks: () => '/afiliados/links',
    affiliateCommissions: () => '/afiliados/comissoes',
    affiliatePayouts: () => '/afiliados/saques',
    affiliateProfile: () => '/afiliados/perfil',
    affiliatePoints: () => '/afiliados/pontos',
    affiliateSupport: () => '/afiliados/suporte',
    careers: () => '/trabalhe-conosco',
    serviceDetail: (id: string) => `/servicos-e-assinaturas/${id}`,
  },
  // Login
  login: {
    root: () => '/login',
    client: () => '/login/pessoa-fisica', // DUPLICADO: aponta para /login/pessoa-fisica
    personal: () => '/login/pessoa-fisica',
    business: () => '/login/empresa',
    businessRegistration: () => '/login/empresa/cadastro',
    restricted: () => '/login/acesso-restrito',
    admin: () => '/login/admin',
    provider: () => '/login/prestador',
    providerRegistration: () => '/login/prestador/cadastro',
    collaborator: () => '/login/colaborador',
    supplier: () => '/fornecedor/login',
    affiliate: () => '/afiliados/login',
    advertiser: () => '/anuncios/login',
    careers: () => '/trabalhe-conosco/acesso',
    recoverPassword: () => '/login/pessoa-fisica/recuperar-senha',
    recoverBusinessPassword: () => '/login/empresa/recuperar-senha',
  },
  // Marketplace GSA
  marketplace: {
    root: () => '/marketplace',
    menu: () => '/marketplace', // DUPLICADO: aponta para /marketplace
    travelPackages: {
      root: () => '/marketplace/menu/pacotes-viagem',
      legacy: () => '/marketplace/pacotes-viagem',
      ofertas: () => '/marketplace/menu/pacotes-viagem/ofertas',
      ofertasNacionais: () => '/marketplace/menu/pacotes-viagem/ofertas/nacionais',
      ofertasInternacionais: () => '/marketplace/menu/pacotes-viagem/ofertas/internacionais',
      ofertasExcursoes: () => '/marketplace/menu/pacotes-viagem/ofertas/excursoes',
      pacote: (slug: string) => `/marketplace/menu/pacotes-viagem/ofertas/${slug}`,
      orcamento: () => '/marketplace/menu/pacotes-viagem/orcamento',
      minhasViagens: () => '/marketplace/menu/pacotes-viagem/minhas-viagens',
      minhaViagem: (id: string) => `/marketplace/menu/pacotes-viagem/minhas-viagens/${id}`,
      minhasPropostas: () => '/marketplace/menu/pacotes-viagem/minhas-propostas',
      minhaProposta: (id: string) => `/marketplace/menu/pacotes-viagem/minhas-propostas/${id}`,
      documentos: () => '/marketplace/menu/pacotes-viagem/documentos',
      cancelamentos: () => '/marketplace/menu/pacotes-viagem/cancelamentos',
      suporte: () => '/marketplace/menu/pacotes-viagem/suporte',
    },
    classifieds: {
      root: () => '/marketplace/menu/classificados',
      imoveis: () => '/marketplace/menu/classificados/imoveis',
      imovel: (slug: string) => `/marketplace/menu/classificados/imoveis/${slug}`,
      veiculos: () => '/marketplace/menu/classificados/veiculos',
      veiculo: (slug: string) => `/marketplace/menu/classificados/veiculos/${slug}`,
      geral: () => '/marketplace/menu/classificados/geral',
      geralItem: (slug: string) => `/marketplace/menu/classificados/geral/${slug}`,
      anunciar: () => '/marketplace/menu/classificados/anunciar',
      anunciarCategoria: (categoria: string) => `/marketplace/menu/classificados/anunciar/${categoria}`,
      editarAnuncio: (id: string) => `/marketplace/menu/classificados/anuncio/${id}/editar`,
      meusAnuncios: () => '/marketplace/menu/classificados/meus-anuncios',
      meuAnuncio: (id: string) => `/marketplace/menu/classificados/meus-anuncios/${id}`,
      interesses: () => '/marketplace/menu/classificados/interesses',
      interesse: (id: string) => `/marketplace/menu/classificados/interesses/${id}`,
      propostas: () => '/marketplace/menu/classificados/propostas',
      proposta: (id: string) => `/marketplace/menu/classificados/propostas/${id}`,
      negociacoes: () => '/marketplace/menu/classificados/negociacoes',
      negociacao: (id: string) => `/marketplace/menu/classificados/negociacoes/${id}`,
      minhasVendas: () => '/marketplace/menu/classificados/minhas-vendas',
      minhaVenda: (id: string) => `/marketplace/menu/classificados/minhas-vendas/${id}`,
      comissoes: () => '/marketplace/menu/classificados/comissoes',
      comissao: (id: string) => `/marketplace/menu/classificados/comissoes/${id}`,
      suporte: () => '/marketplace/menu/classificados/suporte'
    },
    saude: {
      root: () => '/marketplace/menu/saude',
      planos: () => '/marketplace/menu/saude/planos',
      individualFamiliar: () => '/marketplace/menu/saude/planos/individual-familiar',
      empresarial: () => '/marketplace/menu/saude/planos/empresarial',
      odontologico: () => '/marketplace/menu/saude/planos/odontologico',
      plano: (slug: string) => `/marketplace/menu/saude/planos/${slug}`,
      cotacao: () => '/marketplace/menu/saude/cotacao',
      minhasCotacoes: () => '/marketplace/menu/saude/minhas-cotacoes',
      minhaCotacao: (id: string) => `/marketplace/menu/saude/minhas-cotacoes/${id}`,
      minhasPropostas: () => '/marketplace/menu/saude/minhas-propostas',
      minhaProposta: (id: string) => `/marketplace/menu/saude/minhas-propostas/${id}`,
      meusPlanos: () => '/marketplace/menu/saude/meus-planos',
      meuPlano: (id: string) => `/marketplace/menu/saude/meus-planos/${id}`,
      dependentes: () => '/marketplace/menu/saude/dependentes',
      documentos: () => '/marketplace/menu/saude/documentos',
      documento: (id: string) => `/marketplace/menu/saude/documentos/${id}`,
      assessoria: (id: string) => `/marketplace/menu/saude/assessoria/${id}`,
      suporte: () => '/marketplace/menu/saude/suporte',
      ticket: (id: string) => `/marketplace/menu/saude/suporte/${id}`
    },
    seguros: {
      root: () => '/marketplace/menu/seguros',
      modalidades: () => '/marketplace/menu/seguros/modalidades',
      modalidade: (categoria: string) => `/marketplace/menu/seguros/modalidades/${categoria}`,
      oferta: (slug: string) => `/marketplace/menu/seguros/ofertas/${slug}`,
      cotacao: () => '/marketplace/menu/seguros/cotacao',
      cotacaoOferta: (slug: string) => `/marketplace/menu/seguros/cotacao/${slug}`,
      minhasCotacoes: () => '/marketplace/menu/seguros/minhas-cotacoes',
      minhaCotacao: (id: string) => `/marketplace/menu/seguros/minhas-cotacoes/${id}`,
      minhasPropostas: () => '/marketplace/menu/seguros/minhas-propostas',
      minhaProposta: (id: string) => `/marketplace/menu/seguros/minhas-propostas/${id}`,
      minhasApolices: () => '/marketplace/menu/seguros/minhas-apolices',
      minhaApolice: (id: string) => `/marketplace/menu/seguros/minhas-apolices/${id}`,
      assistencias: () => '/marketplace/menu/seguros/assistencias',
      sinistros: () => '/marketplace/menu/seguros/sinistros',
      sinistro: (id: string) => `/marketplace/menu/seguros/sinistros/${id}`,
      documentos: () => '/marketplace/menu/seguros/documentos',
      assessoria: (id: string) => `/marketplace/menu/seguros/assessoria/${id}`,
      suporte: () => '/marketplace/menu/seguros/suporte',
      ticket: (id: string) => `/marketplace/menu/seguros/suporte/${id}`,
    },
    store: {
      root: () => '/marketplace/loja',
      products: () => '/marketplace/loja/produtos',
      product: (id: string) => `/marketplace/loja/produtos/${id}`,
      subscriptions: () => '/marketplace/loja/assinaturas',
      subscription: (id: string) => `/marketplace/loja/assinaturas/${id}`,
      // Sub-visões como abas ou sub-páginas do StoreHub
      compras: () => '/marketplace/loja/compras',
      compra: (id: string) => `/marketplace/loja/compras/${id}`,
      cupons: () => '/marketplace/loja/cupons',
      promocoes: () => '/marketplace/loja/promocoes',
      trocas: () => '/marketplace/loja/trocas',
      reembolsos: () => '/marketplace/loja/reembolsos',
      orderSuccess: (orderId: string) => `/marketplace/loja/pedido-confirmado?orderId=${orderId}`,
      wishlist: () => '/marketplace/loja/wishlist',
      blog: () => '/marketplace/loja/blog',
      blogPost: (id: string) => `/marketplace/loja/blog/${id}`,
    },
  },
  // Portal do Cliente
  client: {
    dashboard: () => '/cliente/dashboard',
    perfil: () => '/cliente/perfil',
    support: () => '/cliente/suporte',
    ticket: (id: string) => `/cliente/suporte/${id}`,
    services: {
      root: () => '/cliente/servicos-e-assinaturas',
      orcamentos: () => '/cliente/servicos-e-assinaturas/orcamentos',
      orcamento: (id: string) => `/cliente/servicos-e-assinaturas/orcamentos/${id}`,
      servicos: () => '/cliente/servicos-e-assinaturas/servicos',
      servico: (id: string) => `/cliente/servicos-e-assinaturas/servicos/${id}`,
      produtos: () => '/cliente/servicos-e-assinaturas/produtos',
      produto: (id: string) => `/cliente/servicos-e-assinaturas/produtos/${id}`,
      assinaturas: () => '/cliente/servicos-e-assinaturas/assinaturas',
      assinatura: (id: string) => `/cliente/servicos-e-assinaturas/assinaturas/${id}`,
    },
    finance: {
      root: () => '/cliente/financeiro',
      faturas: () => '/cliente/financeiro/faturas',
      invoice: (id: string) => `/cliente/financeiro/faturas/${id}`,
      notas: () => '/cliente/financeiro/notas-fiscais',
      nota: (id: string) => `/cliente/financeiro/notas-fiscais/${id}`,
      extrato: () => '/cliente/financeiro/extrato',
      movimentacao: (id: string) => `/cliente/financeiro/extrato/${id}`,
      saques: () => '/cliente/financeiro/saques',
      saque: (id: string) => `/cliente/financeiro/saques/${id}`,
      transferencias: () => '/cliente/financeiro/transferencias',
      transferencia: (id: string) => `/cliente/financeiro/transferencias/${id}`,
      credito: () => '/cliente/financeiro/credito',
      solicitacaoCredito: (id: string) => `/cliente/financeiro/credito/${id}`,
      emprestimos: () => '/cliente/financeiro/emprestimos',
      emprestimo: (id: string) => `/cliente/financeiro/emprestimos/${id}`,
    },
    loyalty: {
      root: () => '/cliente/fidelidade',
      pontos: () => '/cliente/fidelidade/pontos',
      vouchers: () => '/cliente/fidelidade/vouchers',
      voucher: (id: string) => `/cliente/fidelidade/vouchers/${id}`,
      promocoes: () => '/cliente/fidelidade/promocoes',
      promocao: (id: string) => `/cliente/fidelidade/promocoes/${id}`,
      premios: () => '/cliente/fidelidade/premios',
      premio: (id: string) => `/cliente/fidelidade/premios/${id}`,
      indiqueGanhe: () => '/cliente/fidelidade/indique-ganhe',
      affiliates: () => '/cliente/fidelidade/afiliados',
      indicacao: (id: string) => `/cliente/fidelidade/indique-ganhe/${id}`,
      vip: () => '/cliente/fidelidade/area-vip',
    }
  },
  // GSA HUB Empresas
  business: {
    dashboard: () => '/empresa/dashboard',
    profile: () => '/empresa/cadastro',
    support: () => '/empresa/suporte',
    ticket: (id: string) => `/empresa/suporte/${id}`,
    marketplace: () => '/empresa/marketplace',
    operations: {
      root: () => '/empresa/operacoes',
      budgets: () => '/empresa/operacoes/orcamentos',
      budget: (id: string) => `/empresa/operacoes/orcamentos/${id}`,
      services: () => '/empresa/operacoes/servicos',
      service: (id: string) => `/empresa/operacoes/servicos/${id}`,
      products: () => '/empresa/operacoes/produtos',
      product: (id: string) => `/empresa/operacoes/produtos/${id}`,
      subscriptions: () => '/empresa/operacoes/assinaturas',
      subscription: (id: string) => `/empresa/operacoes/assinaturas/${id}`,
    },
    finance: {
      root: () => '/empresa/financeiro',
      invoices: () => '/empresa/financeiro/faturas',
      invoice: (id: string) => `/empresa/financeiro/faturas/${id}`,
      taxDocuments: () => '/empresa/financeiro/notas-fiscais',
      taxDocument: (id: string) => `/empresa/financeiro/notas-fiscais/${id}`,
      statement: () => '/empresa/financeiro/extrato',
      transaction: (id: string) => `/empresa/financeiro/extrato/${id}`,
      withdrawals: () => '/empresa/financeiro/saques',
      withdrawal: (id: string) => `/empresa/financeiro/saques/${id}`,
      transfers: () => '/empresa/financeiro/transferencias',
      transfer: (id: string) => `/empresa/financeiro/transferencias/${id}`,
      credit: () => '/empresa/financeiro/credito',
      creditRequest: (id: string) => `/empresa/financeiro/credito/${id}`,
      loans: () => '/empresa/financeiro/emprestimos',
      loan: (id: string) => `/empresa/financeiro/emprestimos/${id}`,
    },
    benefits: {
      root: () => '/empresa/beneficios',
      points: () => '/empresa/beneficios/pontos',
      vouchers: () => '/empresa/beneficios/vouchers',
      voucher: (id: string) => `/empresa/beneficios/vouchers/${id}`,
      promotions: () => '/empresa/beneficios/promocoes',
      promotion: (id: string) => `/empresa/beneficios/promocoes/${id}`,
      rewards: () => '/empresa/beneficios/premios',
      reward: (id: string) => `/empresa/beneficios/premios/${id}`,
      referrals: () => '/empresa/beneficios/indique-ganhe',
      vip: () => '/empresa/beneficios/area-vip',
    },
  },
  // Portal do Anunciante
  advertiser: {
    root: () => '/anuncios/login', // DUPLICADO: mesma rota de login.advertiser
    login: () => '/anuncios/login',
    proposals: () => '/anuncios/propostas',
    campaigns: () => '/anuncios/campanhas',
    creatives: () => '/anuncios/criativos',
    finance: () => '/anuncios/financeiro',
    reports: () => '/anuncios/relatorios',
  },
  // Administrativo
  admin: {
    dashboard: () => '/admin/dashboard',
    partners: () => '/admin/parceiros',
    trabalheConosco: () => '/admin/trabalhe-conosco',
    ads: () => '/admin/anuncios',
    adRequest: (id: string) => `/admin/anuncios/solicitacoes/${id}`,
    clients: () => '/admin/cadastros/clientes',
    client: (id: string) => `/admin/cadastros/clientes/${id}`,
    providers: () => '/admin/cadastros/prestadores',
    provider: (id: string) => `/admin/cadastros/prestadores/${id}`,
    suppliers: () => '/admin/fornecedores',
    supplier: (id: string) => `/admin/fornecedores/cadastros/${id}`,
    products: () => '/admin/loja/produtos',
    product: (id: string) => `/admin/loja/produtos/${id}`,
    services: () => '/admin/loja/servicos',
    service: (id: string) => `/admin/loja/servicos/${id}`,
    servicePackages: () => '/admin/loja/pacotes',
    subscriptions: () => '/admin/loja/assinaturas',
    subscription: (id: string) => `/admin/loja/assinaturas/${id}`,
    categories: () => '/admin/loja/categorias_loja',
    orcamentos: () => '/admin/operacoes/orcamentos',
    orcamento: (id: string) => `/admin/operacoes/orcamentos/${id}`,
    ordensServico: () => '/admin/operacoes/os',
    ordemServico: (id: string) => `/admin/operacoes/os/${id}`,
    ordensCompra: () => '/admin/operacoes/produtos',
    ordemCompra: (id: string) => `/admin/operacoes/produtos/${id}`,
    ordensAssinatura: () => '/admin/operacoes/assinaturas',
    ordemAssinatura: (id: string) => `/admin/operacoes/assinaturas/${id}`,
    financeiro: () => '/admin/financeiro',
    emprestimos: () => '/admin/financeiro/emprestimos',
    emprestimo: (id: string) => `/admin/financeiro/emprestimos/${id}`,
    creditoLoja: () => '/admin/financeiro/credito',
    creditoLojaItem: (id: string) => `/admin/financeiro/credito/${id}`,
    promocoesQuantidade: () => '/admin/promocoes',
    areaVip: () => '/admin/area_vip',
    cobranca: () => '/admin/cobranca',
    fiscal: () => '/admin/fiscal',
    atendimento: () => '/admin/atendimento',
    relatorios: () => '/admin/relatorios',
    configuracoes: () => '/admin/configuracoes',
    acessos: () => '/admin/acessos',
    sistema: () => '/admin/sistema',
    saude: {
      root: () => '/admin/saude',
      dashboard: () => '/admin/saude/dashboard',
      parceiros: () => '/admin/saude/parceiros',
      produtos: () => '/admin/saude/produtos',
      cotacoes: () => '/admin/saude/cotacoes',
      propostas: () => '/admin/saude/propostas',
      contratos: () => '/admin/saude/contratos',
      assessorias: () => '/admin/saude/assessorias',
      comissoes: () => '/admin/saude/comissoes',
      documentos: () => '/admin/saude/documentos',
      assistencias: () => '/admin/saude/atendimentos', // DUPLICADO: aponta para atendimentos
      sinistros: () => '/admin/saude/atendimentos', // DUPLICADO: aponta para atendimentos
      atendimentos: () => '/admin/saude/atendimentos',
    },
    seguros: {
      root: () => '/admin/seguros',
      dashboard: () => '/admin/seguros/dashboard',
      parceiros: () => '/admin/seguros/parceiros',
      produtos: () => '/admin/seguros/produtos',
      cotacoes: () => '/admin/seguros/cotacoes',
      propostas: () => '/admin/seguros/propostas',
      contratos: () => '/admin/seguros/apolices',
      assessorias: () => '/admin/seguros/assessorias',
      comissoes: () => '/admin/seguros/comissoes',
      documentos: () => '/admin/seguros/documentos',
      assistencias: () => '/admin/seguros/assistencias',
      sinistros: () => '/admin/seguros/sinistros',
      atendimentos: () => '/admin/seguros/atendimentos',
    },
  },
  // Prestador
  provider: {
    home: () => '/prestador',
    login: () => '/login/prestador',
    dashboard: () => '/prestador/dashboard',
    payables: () => '/prestador/financeiro',
    demands: () => '/prestador/demandas',
    demand: (id: string) => `/prestador/demandas/${id}`,
    agenda: () => '/prestador/agenda',
    agendamento: (id: string) => `/prestador/agenda/${id}`,
    financeiro: () => '/prestador/financeiro',
    vouchers: () => '/prestador/vouchers',
    voucher: (id: string) => `/prestador/vouchers/${id}`,
    premios: () => '/prestador/premios',
    premio: (id: string) => `/prestador/premios/${id}`,
    promocoes: () => '/prestador/promocoes',
    promocao: (id: string) => `/prestador/promocoes/${id}`,
    documents: () => '/prestador/documentos',
    document: (id: string) => `/prestador/documentos/${id}`,
    support: () => '/prestador/suporte',
    ticket: (id: string) => `/prestador/suporte/${id}`,
  },
  // Fornecedor (Portal do Fornecedor)
  supplier: {
    home: () => '/fornecedor',
    login: () => '/fornecedor/login',
    dashboard: () => '/fornecedor/dashboard',
    products: () => '/fornecedor/produtos',
    product: (id: string) => `/fornecedor/produtos/${id}`,
    orders: () => '/fornecedor/pedidos',
    order: (id: string) => `/fornecedor/pedidos/${id}`,
    deliveries: () => '/fornecedor/entregas',
    delivery: (id: string) => `/fornecedor/entregas/${id}`,
    payables: () => '/fornecedor/financeiro',
    payable: (id: string) => `/fornecedor/financeiro/${id}`,
    profile: () => '/fornecedor/perfil',
    support: () => '/fornecedor/suporte',
    ticket: (id: string) => `/fornecedor/suporte/${id}`,
  },
};
