-- Authentication hardening: credentials are verified and the application session
-- is created in the same database transaction. Session creation itself is private.

CREATE TABLE IF NOT EXISTS public.gsa_auth_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escopo text NOT NULL,
  chave_hash text NOT NULL,
  sucesso boolean NOT NULL DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_gsa_auth_attempts_rate_limit
  ON public.gsa_auth_attempts (escopo, chave_hash, criado_em DESC)
  WHERE sucesso = false;

ALTER TABLE public.gsa_auth_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.gsa_auth_attempts FROM public, anon, authenticated;

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS value_hash text;

ALTER TABLE public.colaboradores
  ADD COLUMN IF NOT EXISTS credencial_hash text;

UPDATE public.system_settings
   SET value_hash = extensions.crypt(value, extensions.gen_salt('bf', 12))
 WHERE key = 'admin_access_code'
   AND value_hash IS NULL
   AND nullif(value, '') IS NOT NULL;

UPDATE public.colaboradores
   SET credencial_hash = extensions.crypt(credencial_acesso, extensions.gen_salt('bf', 12))
 WHERE credencial_hash IS NULL
   AND nullif(credencial_acesso, '') IS NOT NULL;

CREATE OR REPLACE FUNCTION public.gsa_request_ip()
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = public
AS $$
DECLARE
  v_headers jsonb;
BEGIN
  BEGIN
    v_headers := nullif(current_setting('request.headers', true), '')::jsonb;
  EXCEPTION WHEN others THEN
    v_headers := '{}'::jsonb;
  END;

  RETURN coalesce(
    nullif(split_part(v_headers ->> 'x-forwarded-for', ',', 1), ''),
    nullif(v_headers ->> 'cf-connecting-ip', ''),
    nullif(v_headers ->> 'x-real-ip', ''),
    'unknown'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_assert_auth_rate_limit(
  p_escopo text,
  p_identificador text,
  p_limite integer DEFAULT 10,
  p_janela interval DEFAULT interval '15 minutes'
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_hash text;
  v_count integer;
BEGIN
  v_hash := public.gsa_hash_session_token(
    coalesce(p_escopo, '') || ':' || coalesce(p_identificador, '') || ':' || public.gsa_request_ip()
  );

  DELETE FROM public.gsa_auth_attempts
   WHERE criado_em < now() - interval '2 days';

  SELECT count(*)
    INTO v_count
  FROM public.gsa_auth_attempts
  WHERE escopo = p_escopo
    AND chave_hash = v_hash
    AND sucesso = false
    AND criado_em >= now() - p_janela;

  IF v_count >= greatest(p_limite, 1) THEN
    RAISE EXCEPTION 'Muitas tentativas de acesso. Aguarde alguns minutos e tente novamente.';
  END IF;

  RETURN v_hash;
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_record_auth_attempt(
  p_escopo text,
  p_chave_hash text,
  p_sucesso boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.gsa_auth_attempts(escopo, chave_hash, sucesso)
  VALUES (p_escopo, p_chave_hash, coalesce(p_sucesso, false));

  IF p_sucesso THEN
    DELETE FROM public.gsa_auth_attempts
     WHERE escopo = p_escopo
       AND chave_hash = p_chave_hash
       AND sucesso = false;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_create_session_internal(
  p_ator_tipo text,
  p_ator_id uuid,
  p_ator_nome text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_token text;
  v_sessao_id uuid;
BEGIN
  IF p_ator_tipo NOT IN ('admin', 'colaborador', 'cliente', 'prestador') THEN
    RAISE EXCEPTION 'Tipo de ator invalido.';
  END IF;
  IF p_ator_id IS NULL THEN
    RAISE EXCEPTION 'Ator obrigatorio.';
  END IF;

  UPDATE public.sistema_sessoes
     SET status = 'encerrado',
         encerrado_em = coalesce(encerrado_em, now())
   WHERE ator_id = p_ator_id
     AND ator_tipo = p_ator_tipo
     AND status = 'ativo';

  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  INSERT INTO public.sistema_sessoes(
    ator_tipo, ator_id, ator_nome, status, token_hash, token_hint, origem, metadata
  ) VALUES (
    p_ator_tipo,
    p_ator_id,
    coalesce(nullif(trim(p_ator_nome), ''), 'Usuario'),
    'ativo',
    public.gsa_hash_session_token(v_token),
    left(v_token, 8),
    'login_atomico',
    coalesce(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_sessao_id;

  RETURN jsonb_build_object(
    'sessao_id', v_sessao_id,
    'session_token', v_token,
    'ator_tipo', p_ator_tipo,
    'ator_id', p_ator_id,
    'ator_nome', coalesce(nullif(trim(p_ator_nome), ''), 'Usuario'),
    'metadata', coalesce(p_metadata, '{}'::jsonb)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.gsa_create_session_internal(text, uuid, text, jsonb)
  FROM public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.gsa_lookup_portal_account(
  p_documento text,
  p_tipo text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_record record;
  v_documento text := regexp_replace(coalesce(p_documento, ''), '\D', '', 'g');
BEGIN
  IF p_tipo = 'cliente' THEN
    SELECT id, nome, status, cadastro_aprovado, pin_hash, pin_bloqueado
      INTO v_record
    FROM public.clientes
    WHERE regexp_replace(coalesce(cpf, cnpj, ''), '\D', '', 'g') = v_documento
    LIMIT 1;
  ELSIF p_tipo = 'prestador' THEN
    SELECT id, nome_razao AS nome, status, true AS cadastro_aprovado, pin_hash, pin_bloqueado
      INTO v_record
    FROM public.prestadores
    WHERE regexp_replace(coalesce(documento, ''), '\D', '', 'g') = v_documento
    LIMIT 1;
  ELSE
    RAISE EXCEPTION 'Tipo de acesso invalido.';
  END IF;

  IF v_record.id IS NULL THEN
    RETURN jsonb_build_object('exists', false);
  END IF;

  RETURN jsonb_build_object(
    'exists', true,
    'id', v_record.id,
    'nome', v_record.nome,
    'status', v_record.status,
    'cadastro_aprovado', v_record.cadastro_aprovado,
    'has_pin', v_record.pin_hash IS NOT NULL,
    'blocked', coalesce(v_record.pin_bloqueado, false)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_login_pin(
  p_documento text,
  p_pin text,
  p_tipo text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_record record;
  v_documento text := regexp_replace(coalesce(p_documento, ''), '\D', '', 'g');
  v_scope text;
  v_rate_key text;
  v_attempts integer;
  v_session jsonb;
BEGIN
  IF p_tipo NOT IN ('cliente', 'prestador') THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Tipo de acesso invalido.');
  END IF;
  IF p_pin !~ '^\d{4}$' THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Senha invalida.');
  END IF;

  v_scope := 'pin_' || p_tipo;
  v_rate_key := public.gsa_assert_auth_rate_limit(v_scope, v_documento, 8, interval '15 minutes');

  IF p_tipo = 'cliente' THEN
    SELECT id, nome, status, cadastro_aprovado, pin_hash, pin_tentativas, pin_bloqueado
      INTO v_record
    FROM public.clientes
    WHERE regexp_replace(coalesce(cpf, cnpj, ''), '\D', '', 'g') = v_documento
    LIMIT 1
    FOR UPDATE;
  ELSE
    SELECT id, nome_razao AS nome, status, true AS cadastro_aprovado,
           pin_hash, pin_tentativas, pin_bloqueado
      INTO v_record
    FROM public.prestadores
    WHERE regexp_replace(coalesce(documento, ''), '\D', '', 'g') = v_documento
    LIMIT 1
    FOR UPDATE;
  END IF;

  IF v_record.id IS NULL OR v_record.pin_hash IS NULL THEN
    PERFORM public.gsa_record_auth_attempt(v_scope, v_rate_key, false);
    RETURN jsonb_build_object('valid', false, 'error', 'Credenciais invalidas.');
  END IF;

  IF coalesce(v_record.pin_bloqueado, false) THEN
    RETURN jsonb_build_object('valid', false, 'error', 'blocked', 'nome', v_record.nome);
  END IF;

  IF p_tipo = 'cliente'
     AND v_record.status = 'inativo'
     AND coalesce(v_record.cadastro_aprovado, true) THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Cliente inativo. Entre em contato com o suporte.');
  END IF;

  IF p_tipo = 'prestador' AND v_record.status IN ('suspenso', 'desligado', 'reprovado') THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Cadastro bloqueado ou indisponivel.');
  END IF;

  IF extensions.crypt(p_pin, v_record.pin_hash) <> v_record.pin_hash THEN
    v_attempts := coalesce(v_record.pin_tentativas, 0) + 1;

    IF p_tipo = 'cliente' THEN
      UPDATE public.clientes
         SET pin_tentativas = v_attempts,
             pin_bloqueado = v_attempts >= 4
       WHERE id = v_record.id;
    ELSE
      UPDATE public.prestadores
         SET pin_tentativas = v_attempts,
             pin_bloqueado = v_attempts >= 4
       WHERE id = v_record.id;
    END IF;

    PERFORM public.gsa_record_auth_attempt(v_scope, v_rate_key, false);

    IF v_attempts >= 4 THEN
      IF NOT EXISTS (
        SELECT 1 FROM public.notificacoes
         WHERE destinatario_tipo = 'admin'
           AND item_id = v_record.id::text
           AND acao_origem = 'bloqueio_login'
           AND data_criacao >= now() - interval '1 day'
      ) THEN
        INSERT INTO public.notificacoes(
          titulo, mensagem, modulo, tab, item_id, tipo,
          destinatario_tipo, prioridade, acao_origem
        ) VALUES (
          'Acesso Bloqueado',
          'A conta de ' || v_record.nome || ' foi bloqueada por excesso de tentativas de senha.',
          'cadastro',
          CASE WHEN p_tipo = 'cliente' THEN 'clientes' ELSE 'prestadores' END,
          v_record.id::text,
          'sistema',
          'admin',
          'alta',
          'bloqueio_login'
        );
      END IF;
      RETURN jsonb_build_object('valid', false, 'error', 'blocked', 'just_blocked_now', true);
    END IF;

    RETURN jsonb_build_object(
      'valid', false,
      'error', 'wrong_pin',
      'attempts_left', 4 - v_attempts
    );
  END IF;

  IF p_tipo = 'cliente' THEN
    UPDATE public.clientes SET pin_tentativas = 0 WHERE id = v_record.id;
  ELSE
    UPDATE public.prestadores SET pin_tentativas = 0 WHERE id = v_record.id;
  END IF;

  v_session := public.gsa_create_session_internal(
    p_tipo, v_record.id, v_record.nome, '{}'::jsonb
  );
  PERFORM public.gsa_record_auth_attempt(v_scope, v_rate_key, true);

  RETURN jsonb_build_object(
    'valid', true,
    'id', v_record.id,
    'nome', v_record.nome,
    'status', v_record.status,
    'session', v_session
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_set_pin_and_login(
  p_documento text,
  p_telefone text,
  p_pin text,
  p_tipo text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_record record;
  v_documento text := regexp_replace(coalesce(p_documento, ''), '\D', '', 'g');
  v_telefone text := regexp_replace(coalesce(p_telefone, ''), '\D', '', 'g');
  v_rate_key text;
  v_session jsonb;
BEGIN
  IF p_tipo NOT IN ('cliente', 'prestador') OR p_pin !~ '^\d{4}$' THEN
    RETURN jsonb_build_object('success', false, 'error', 'Dados de acesso invalidos.');
  END IF;
  IF length(v_telefone) < 10 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Informe o telefone cadastrado com DDD.');
  END IF;

  v_rate_key := public.gsa_assert_auth_rate_limit('primeiro_acesso_' || p_tipo, v_documento, 5, interval '30 minutes');

  IF p_tipo = 'cliente' THEN
    SELECT id, nome, status, cadastro_aprovado, telefone, pin_hash
      INTO v_record
    FROM public.clientes
    WHERE regexp_replace(coalesce(cpf, cnpj, ''), '\D', '', 'g') = v_documento
    LIMIT 1
    FOR UPDATE;
  ELSE
    SELECT id, nome_razao AS nome, status, true AS cadastro_aprovado, telefone, pin_hash
      INTO v_record
    FROM public.prestadores
    WHERE regexp_replace(coalesce(documento, ''), '\D', '', 'g') = v_documento
    LIMIT 1
    FOR UPDATE;
  END IF;

  IF v_record.id IS NULL
     OR regexp_replace(coalesce(v_record.telefone, ''), '\D', '', 'g') <> v_telefone THEN
    PERFORM public.gsa_record_auth_attempt('primeiro_acesso_' || p_tipo, v_rate_key, false);
    RETURN jsonb_build_object('success', false, 'error', 'Documento ou telefone nao conferem com o cadastro.');
  END IF;

  IF v_record.pin_hash IS NOT NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'A senha ja foi cadastrada. Use a tela de login.');
  END IF;

  IF p_tipo = 'cliente'
     AND v_record.status = 'inativo'
     AND coalesce(v_record.cadastro_aprovado, true) THEN
    RETURN jsonb_build_object('success', false, 'error', 'Cliente inativo. Entre em contato com o suporte.');
  END IF;
  IF p_tipo = 'prestador' AND v_record.status IN ('suspenso', 'desligado', 'reprovado') THEN
    RETURN jsonb_build_object('success', false, 'error', 'Cadastro bloqueado ou indisponivel.');
  END IF;

  IF p_tipo = 'cliente' THEN
    UPDATE public.clientes
       SET pin_hash = extensions.crypt(p_pin, extensions.gen_salt('bf', 12)),
           pin_tentativas = 0,
           pin_bloqueado = false
     WHERE id = v_record.id;
  ELSE
    UPDATE public.prestadores
       SET pin_hash = extensions.crypt(p_pin, extensions.gen_salt('bf', 12)),
           pin_tentativas = 0,
           pin_bloqueado = false
     WHERE id = v_record.id;
  END IF;

  v_session := public.gsa_create_session_internal(
    p_tipo, v_record.id, v_record.nome, '{}'::jsonb
  );
  PERFORM public.gsa_record_auth_attempt('primeiro_acesso_' || p_tipo, v_rate_key, true);

  RETURN jsonb_build_object(
    'success', true,
    'id', v_record.id,
    'nome', v_record.nome,
    'session', v_session
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_login_admin(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_setting record;
  v_rate_key text;
  v_session jsonb;
BEGIN
  v_rate_key := public.gsa_assert_auth_rate_limit('admin', 'master', 8, interval '30 minutes');

  SELECT value, value_hash, must_change_code
    INTO v_setting
  FROM public.system_settings
  WHERE key = 'admin_access_code'
  LIMIT 1
  FOR UPDATE;

  IF v_setting.value_hash IS NULL
     OR extensions.crypt(coalesce(p_code, ''), v_setting.value_hash) <> v_setting.value_hash THEN
    PERFORM public.gsa_record_auth_attempt('admin', v_rate_key, false);
    RETURN jsonb_build_object('valid', false, 'error', 'Codigo de acesso invalido.');
  END IF;

  v_session := public.gsa_create_session_internal(
    'admin',
    '00000000-0000-0000-0000-000000000000'::uuid,
    'Administrador',
    '{}'::jsonb
  );
  PERFORM public.gsa_record_auth_attempt('admin', v_rate_key, true);

  RETURN jsonb_build_object(
    'valid', true,
    'must_change', coalesce(v_setting.must_change_code, false),
    'session', v_session
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gsa_login_colaborador(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_colaborador record;
  v_modulos jsonb;
  v_rate_key text;
  v_session jsonb;
BEGIN
  v_rate_key := public.gsa_assert_auth_rate_limit('colaborador', 'painel', 10, interval '30 minutes');

  SELECT * INTO v_colaborador
  FROM public.colaboradores
  WHERE status = 'ativo'
    AND credencial_hash IS NOT NULL
    AND extensions.crypt(coalesce(p_code, ''), credencial_hash) = credencial_hash
  LIMIT 1;

  IF v_colaborador.id IS NULL THEN
    PERFORM public.gsa_record_auth_attempt('colaborador', v_rate_key, false);
    RETURN jsonb_build_object('valid', false, 'error', 'Credencial invalida ou colaborador inativo.');
  END IF;

  SELECT coalesce(jsonb_agg(modulo_id ORDER BY modulo_id), '[]'::jsonb)
    INTO v_modulos
  FROM public.colaborador_modulos
  WHERE colaborador_id = v_colaborador.id;

  v_session := public.gsa_create_session_internal(
    'colaborador',
    v_colaborador.id,
    v_colaborador.nome,
    jsonb_build_object('modulos', v_modulos)
  );
  PERFORM public.gsa_record_auth_attempt('colaborador', v_rate_key, true);

  RETURN jsonb_build_object(
    'valid', true,
    'id', v_colaborador.id,
    'nome', v_colaborador.nome,
    'modulos', v_modulos,
    'session', v_session
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.gsa_start_session(text, uuid, text, jsonb) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.gsa_check_active_session(uuid) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.gsa_force_end_session(uuid) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.verify_admin_access(text) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.verify_colaborador_access(text) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.verify_pin(text, text, text) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_pin(text, text, text) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.gsa_request_ip() FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.gsa_assert_auth_rate_limit(text, text, integer, interval) FROM public, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.gsa_record_auth_attempt(text, text, boolean) FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.gsa_lookup_portal_account(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gsa_login_pin(text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gsa_set_pin_and_login(text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gsa_login_admin(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gsa_login_colaborador(text) TO anon, authenticated;

